<section class="panel">
    <header class="panel-heading">CADASTRO DE TIPO DE DOCUMENTO</header>
    <div class="panel-body">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "editar")); ?>" method="post" id="formulario" class="formulario">
            <input type="hidden" name="id" id="id" value="<?php echo $this->registro->getId(); ?>" />
            <?php if ($this->registro->getId()) { ?>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="codigo">Código:</label>
                    <input type="text" name="codigo" id="codigo" maxlength="60" value="<?php echo $this->registro->getId(); ?>" class="form-control" disabled/>
                </div>
            </div>
            <?php } ?>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table("id_documento_tipo_target");
                $ctrl->setModel("TbDocumentoTipoTarget");
                $ctrl->setPkName("id_documento_tipo_target");
                $ctrl->setValue($this->registro->id_documento_tipo_target);
                $ctrl->setAttrib('class', 'form-control');
                $ctrl->setLabel("Tipo");
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="chave">Chave:</label>
                    <input type="text" name="chave" id="chave" size="10" maxlength="10" value="<?php echo $this->registro->chave; ?>" class="form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="descricao">Descrição:</label>
                    <input type="text" name="descricao" id="descricao" size="60" maxlength="60" value="<?php echo $this->registro->descricao; ?>" class="form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="possui_numero"Possui Número:</label>
                    <select name="possui_numero" id="possui_numero" class="form-control">
                        <option value="" <?php echo (!$this->registro->possui_numero)?"selected":""; ?>>==> SELECIONE <==</option>
                        <option value="S" <?php echo ($this->registro->possui_numero == "S")?"selected":""; ?>>SIM</option>
                        <option value="N" <?php echo ($this->registro->possui_numero == "N")?"selected":""; ?>>NÃO</option>
                    </select>
                </div>

            </div>
        </form>
    </div>
</section>