<?php 
$txt_tipo = $txt_numero = $txt_beneficiario = $txt_status = $txt_data_validade = $txt_justificativa = $txt_resposta = "";
if (isset($this->credencial)) {
    $registro = $this->credencial;
    $ct = $registro->findParentRow("TbCredencialTipo");
    if ($ct) {
        $txt_tipo = $ct->toString();
    }
    $numero = $registro->mostrarNumero();
    if (!empty($numero)) {
        $txt_numero = $numero;
    }
    $pf = $registro->pegaBeneficiario();
    if ($pf) {
        $txt_beneficiario = $pf->toString();
    }
    $cs = $registro->findParentRow("TbCredencialStatus");
    if ($cs) {
        $txt_status = $cs->toString();
    }
}
if ($this->justificativa) {
    $txt_justificativa = $this->justificativa;
}
if ($this->data_validade) {
    $txt_data_validade = $this->data_validade;
}
if (!$txt_data_validade) {
    $data_validade = new Zend_Date();
    $data_validade->add(1, Zend_Date::YEAR);
    $txt_data_validade = $data_validade->toString("dd/MM/yyyy");    
}
if ($this->resposta) {
    $txt_resposta = $this->resposta;
}
?>
<script type="text/javascript">
    $(document).ready(function() {
        $("#resposta").change(function() {
            $(".linha_data_validade, .linha_justificativa").hide();
            if (!$(this).val().length) {
                return false;
            }
            if ($(this).val() == "D") {
                $(".linha_data_validade").show();
            } else if ($(this).val() == "I") {
                $(".linha_justificativa").show();
            }
        }).change();
        $("#resposta").focus();
    });
</script>
<section class="panel">
    <header class="panel-heading">
        DEFERIR / INDEFERIR
    </header>
    <div class="panel-body">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => $this->getRequest()->getActionName())); ?>" method="post" id="formulario" class="formulario">
            <dl class="dl-horizontal">
                <dt>Tipo:</dt>
                <dd><?php echo $txt_tipo; ?></dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>Número:</dt>
                <dd><?php echo $txt_numero; ?></dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>Beneficiário:</dt>
                <dd><?php echo $txt_beneficiario; ?></dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>Status:</dt>
                <dd><?php echo $txt_status; ?></dd>
            </dl>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="resposta">Resposta:</label>
                    <select name="resposta" id="resposta" class="form-control">
                        <option value="" <?php echo (!$txt_resposta)?"selected":""; ?>>==> SELECIONE <==</option>
                        <option value="D" <?php echo ($txt_resposta == "D")?"selected":""; ?>>DEFERIR</option>
                        <option value="I" <?php echo ($txt_resposta == "I")?"selected":""; ?>>INDEFERIR</option>
                    </select>
                </div>
            </div>
            <div class="col-md-4 linha_data_validade" style="display:none">
                <div class="form-group">
                    <label for="resposta_data_validade">Data de Validade:</label>
                    <input type="text" name="data_validade" id="data_validade" value="<?php echo $txt_data_validade; ?>" class="form-control data" />
                </div>
            </div>
            <div class="col-md-4 linha_justificativa" style="display:none">
                <div class="form-group">
                    <label for="justificativa">Justificativa:</label>
                    <textarea name="justificativa" id="justificativa" rows="5" class="form-control"><?php echo $txt_justificativa; ?></textarea>
                </div>
            </div>
        </form>
    </div>
</section>