<?php 
$txt_tipo = $txt_numero = $txt_beneficiario = $txt_status = $txt_validade = "";
if (isset($this->credencial)) {
    $registro = $this->credencial;
    $ct = $registro->findParentRow("TbCredencialTipo");
    if ($ct) {
        $txt_tipo = $ct->toString();
    }
    $numero = $registro->mostrarNumero();
    if (!empty($numero)) {
        $txt_numero = $numero;
    }
    $pf = $registro->pegaBeneficiario();
    if ($pf) {
        $txt_beneficiario = $pf->toString();
    }
    $txt_status = $registro->getStatus();
}
if ($this->validade) {
    $txt_validade = $this->validade;
}
?>
<section class="panel">
    <header class="panel-heading">
        RENOVAR CREDENCIAL
    </header>
    <div class="panel-body">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => $this->getRequest()->getActionName())); ?>" method="post" id="formulario" class="formulario">
            <dl class="dl-horizontal">
                <dt>Tipo:</dt>
                <dd><?php echo $txt_tipo; ?></dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>Número:</dt>
                <dd><?php echo $txt_numero; ?></dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>Beneficiário:</dt>
                <dd><?php echo $txt_beneficiario; ?></dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>Status:</dt>
                <dd><?php echo $txt_status; ?></dd>
            </dl>
            <div class="col-md-4">
                <div class="form-group" >
                    <label for="validade" class="control-label">Renovar em:</label>
                    <input type="text" name="validade" id="validade" class="form-control" value="<?php echo $this->validade; ?>" />   Anos
                </div>
            </div>
        </form>
    </div>
</section>
<script type="text/javascript">
    $(document).ready(function() {
        $("#validade").focus().select();
    });
</script>