<section class="panel">
    <header class="panel-heading">
        Visualizar Prioridade
    </header>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>Código:</dt>
            <dd><?php echo $this->registro->getId(); ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Chave:</dt>
            <dd><?php echo $this->registro->chave; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Descrição:</dt>
            <dd><?php echo $this->registro->descricao; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Tolerância:</dt>
            <dd><?php echo $this->registro->tolerancia; ?></dd>
        </dl>
    </div>
</section>