<section class="panel" id="idPesquisa" style="display: none">
    <header class="panel-heading">
        Opções de Pesquisa
    </header>
    <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "index")); ?>" method="post" id="formulario" class="formulario">
    <div class="panel-body">
        <div class="col-md-4">
            <div class="form-group">
                <label for="filtro_operacao"">Operação:</label>
                <input type="text" class="filtro form-control" name="filtro_operacao" id="filtro_operacao" value="<?php echo $this->dados["filtro_operacao"]; ?>" />
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="filtro_tabela"">Tabela:</label>
                <input type="text" class="filtro form-control" name="filtro_tabela" id="filtro_tabela" value="<?php echo $this->dados["filtro_tabela"]; ?>" />
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="filtro_cpf"">C.P.F.:</label>
                <input type="text" name="filtro_cpf" id="filtro_cpf" value="<?php echo $this->dados["filtro_cpf"]; ?>" class="filtro cpf form-control" />
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="filtro_nome"">Nome:</label>
                <input type="text" class="filtro form-control" name="filtro_nome" id="filtro_nome" value="<?php echo $this->dados["filtro_nome"]; ?>" />
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="filtro_id"">Identificador do Registro:</label>
                <input type="text" class="filtro form-control" name="filtro_id" id="filtro_id" value="<?php echo $this->dados["filtro_id"]; ?>" />
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="filtro_data_inicio"">Data Início:</label>
                <input type="text" class="filtro data form-control" name="filtro_data_inicio" id="filtro_data_inicio" value="<?php echo $this->dados["filtro_data_inicio"]; ?>" />
            </div>
        </div>
        <div class="col-md-4">
            <div class="control-group">
                <label for="filtro_data_final"">Data Fim:</label>
                <input type="text" class="filtro data form-control" name="filtro_data_final" id="filtro_data_final" value="<?php echo $this->dados["filtro_data_final"]; ?>" />
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="form-group">
            <input type="submit" value="Pesquisar" class="acao btn btn-primary"  />
        </div>
    </div>
    </form>
</section>
<section class="panel">
    <header class="panel-heading">
        Logs
    </header>
    <table class="table table-striped table-hover table-vcenter">
        <thead>
        <tr>
            <th>Data / Hora</th>
            <th>Operação</th>
            <th>Tabela</th>
            <th>C.P.F.</th>
            <th>Usuário</th>
            <th>Identificador Registro</th>
            <th width="20px">Operações</th>
        </tr>
        </thead>
        <?php if ($this->registros && count($this->registros)) { ?>
            <tbody>
            <?php
            foreach ($this->registros as $registro) {
                $registro = TbLog::pegaPorId($registro["id_log"]);
                $data = new Zend_Date($registro->data);
                $txt_cpf = $txt_nome = "--";
                if ($registro->cpf) {
                    $txt_cpf = Escola_Util::formatCpf($registro->cpf);
                }
                if ($registro->nome) {
                    $txt_nome = $registro->nome;
                }
                ?>
                <tr>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo $data->get("dd/MM/Y HH:mm:ss"); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo $registro->findParentRow("TbLogOperacao")->toString(); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo $registro->tabela; ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo $txt_cpf; ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo $txt_nome; ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo $registro->id; ?>
                        </a>
                    </td>
                    <td width="20px">
                        <div align="center">
                            <a class="btn btn-white" data-container="body" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "view",
                                "id" => $registro->getId())); ?>" class="" title="Visualiar" data-toogle="tooltip">
                                <i class="icon-search"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        <?php } ?>
    </table>
    <div class="panel-footer">
        <?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
    </div>
</section>