<section class="panel">
    <header class="panel-heading">DADOS PESSOAIS</header>
    <div class="panel-body">
        <form action="<?php echo $this->url(array("controller" => "funcionario", "action" => "addfuncionario")); ?>" method="post" id="formulario" class="formulario">
            <?php if ($this->funcionario->getId()) { ?>
                <input type="hidden" name="id_funcionario" id="id_funcionario" value="<?php echo $this->funcionario->getId(); ?>" />
            <?php } ?>
            <?php if ($this->pf->getId()) { ?>
                <input type="hidden" name="id_pessoa_fisica" id="id_pessoa_fisica" value="<?php echo $this->pf->getId(); ?>" />
            <?php } ?>
            <?php if ($this->pf->pega_pessoa()->getId()) { ?>
                <input type="hidden" name="id_pessoa" id="id_pessoa" value="<?php echo $this->pf->pega_pessoa()->getId(); ?>" />
            <?php } ?>
            <?php if ($this->lotacao->getId()) { ?>
                <input type="hidden" name="id_lotacao" id="id_lotacao" value="<?php echo $this->lotacao->getId(); ?>" />
            <?php } ?>
            <input type="hidden" name="cpf" id="cpf" value="<?php echo $this->pf->cpf; ?>" />
            <div class="col-md-4">
                <label for="Nome">CPF:</label>
                <input type="text" name="cpf"  maxlength="50" value="<?php echo $this->formatCpf($this->pf->cpf); ?>" class="form-control" disabled/>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="Nome">Nome:</label>
                    <input type="text" name="nome" id="nome" maxlength="50" value="<?php echo $this->pf->nome; ?>" class="form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="email">E-Mail:</label>
                    <input type="text" name="email" id="email" maxlength="60" value="<?php echo $this->pf->pega_pessoa()->email; ?>" class="form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="data_nascimento">Data de Nascimento:</label>
                    <input type="text" name="data_nascimento" id="data_nascimento" value="<?php echo $this->pf->mostrarDataNascimento(); ?>" class="data form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="nome_mae">Nome da Mãe:</label>
                    <input type="text" name="nome_mae" id="nome_mae" maxlength="50" value="<?php echo $this->pf->nome_mae; ?>" class="form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="identidade_numero">Identidade - Número:</label>
                    <input type="text" name="identidade_numero" id="identidade_numero" maxlength="30" value="<?php echo $this->pf->identidade_numero; ?>" class="form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="identidade_orgao_expedidor">Identidade - Órgão Expedidor:</label>
                    <input type="text" name="identidade_orgao_expedidor" id="identidade_orgao_expedidor" maxlength="20" value="<?php echo $this->pf->identidade_orgao_expedidor; ?>" class="form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table("identidade_id_uf");
                $ctrl->setPkName("id_uf");
                $ctrl->setModel("TbUf");
                $ctrl->setValue($this->pf->identidade_id_uf);
                $ctrl->setLabel("Identidade - UF: ");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table("id_setor");
                $ctrl->setPkName("id_setor");
                $ctrl->setModel("TbSetor");
                $ctrl->setValue($this->lotacao->id_setor);
                $ctrl->setLabel("Setor: ");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table("id_funcionario_tipo");
                $ctrl->setPkName("id_funcionario_tipo");
                $ctrl->setModel("TbFuncionarioTipo");
                $ctrl->setValue($this->funcionario->id_funcionario_tipo);
                $ctrl->setLabel("Tipo de Vínculo: ");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="matricula">Matrícula:</label>
                    <input type="text" name="matricula" id="matricula" maxlength="20" value="<?php echo $this->funcionario->matricula; ?>" class="form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table_Crud_Cargo("id_cargo");
                $ctrl->setPkName("id_cargo");
                $ctrl->setModel("TbCargo");
                $ctrl->setValue($this->funcionario->id_cargo);
                $ctrl->setLabel("Cargo: ");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="data_ingresso">Data de Ingresso:</label>
                    <div class="controls">
                        <input type="text" name="data_ingresso" id="data_ingresso" value="<?php echo $this->funcionario->mostrarDataIngresso(); ?>" class="data form-control" />
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table("id_funcionario_situacao");
                $ctrl->setPkName("id_funcionario_situacao");
                $ctrl->setModel("TbFuncionarioSituacao");
                $ctrl->setValue($this->funcionario->id_funcionario_situacao);
                $ctrl->setLabel("Situação: ");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
        </form>
    </div>
</section>