<section class="panel">
    <header class="panel-heading">
        CADASTRO DE OCORRÊNCIA
    </header>
    <div class="panel-body">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "editarocorrencia")); ?>" method="post" id="formulario" class="formulario">
            <input type="hidden" name="id_funcionario" id="id_funcionario" value="<?php echo $this->funcionario->getId(); ?>" />
            <?php if ($this->registro->getId()) { ?>
                <input type="hidden" name="id_ocorrencia" id="id_ocorrencia" value="<?php echo $this->registro->getId(); ?>" />
            <?php } ?>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="funcionario">Funcionário:</label>
                    <input type="text" name="funcionario" id="funcionario" value="<?php echo $this->funcionario->toString(); ?>" class="form-control" disabled />
                </div>
            </div>

            <?php if ($this->registro->getId()) { ?>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="codigo">Código:</label>
                        <input type="text" name="codigo" id="codigo" value="<?php echo $this->registro->getId(); ?>" class="form-control" disabled />
                    </div>
                </div>
            <?php } ?>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table("id_funcionario_ocorrencia_tipo");
                $ctrl->setPkName("id_funcionario_ocorrencia_tipo");
                $ctrl->setModel("TbFuncionarioOcorrenciaTipo");
                $ctrl->setValue($this->registro->id_funcionario_ocorrencia_tipo);
                $ctrl->setLabel("Tipo: ");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="data_inicial">Data Inicial:</label>
                    <input type="text" name="data_inicio" id="data_inicio" value="<?php echo $this->formatData($this->registro->data_inicio); ?>" class="data form-control" />

                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="data_final">Data Final:</label>
                    <input type="text" name="data_final" id="data_final" value="<?php echo $this->formatData($this->registro->data_final); ?>" class="data form-control" />

                </div>
            </div>
            <div class="col-md-8">
                <div class="form-group">
                    <label for="observacoes">Observações:</label>
                    <textarea name="observacoes" id="observacoes" class="form-control"><?php echo $this->registro->observacoes; ?></textarea>
                </div>
            </div>
        </form>
    </div>
</section>