<form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "index")); ?>" method="post" id="formulario" class="formulario" enctype="multipart/form-data">
    <section class="panel" id="idPesquisa" style="display: none">
        <header class="panel-heading">Opções de Pesquisa</header>
        <div class="panel-body">
            <div class="col-md-4">
                <div class="form-group">
                    <label for="filtro_cargo">Cargo:</label>
                    <input type="text" class="filtro form-control" name="filtro_cargo" id="filtro_cargo" value="<?php echo $this->dados["filtro_cargo"]; ?>" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="filtro_setor">Setor:</label>
                    <input type="text" class="filtro form-control" name="filtro_setor" id="filtro_setor" value="<?php echo $this->dados["filtro_setor"]; ?>" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="filtro_matricula">Matrícula:</label>
                    <input type="text" class="filtro form-control" name="filtro_matricula" id="filtro_matricula" value="<?php echo $this->dados["filtro_matricula"]; ?>" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="filtro_cpf">C.P.F.:</label>
                    <input type="text" name="filtro_cpf " id="filtro_cpf" value="<?php echo $this->dados["filtro_cpf"]; ?>" class="filtro cpf form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="filtro_nome">Nome:</label>
                    <input type="text" class="filtro form-control" name="filtro_nome" id="filtro_nome" value="<?php echo $this->dados["filtro_nome"]; ?>" />
                </div>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table("filtro_id_funcionario_situacao");
                $ctrl->setAttrib("class", "filtro");
                $ctrl->setPkName("id_funcionario_situacao");
                $ctrl->setModel("TbFuncionarioSituacao");
                $ctrl->setValue($this->dados["filtro_id_funcionario_situacao"]);
                $ctrl->setLabel("Situação do Servidor:");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <input type="submit" value="Pesquisar" class="acao btn btn-primary" />
                    <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />
                </div>
            </div>
        </div>
    </section>
    <section class="panel importar" id="importar" style="display: none">
        <header class="panel-heading">Importar</header>
        <div class="panel-body">
            <div class="col-md-4">
                <div class="form-group">
                    <label for="arquivo">Arquivo de Dados (CSV):</label>
                    <input type="file" name="arquivo" id="arquivo" class="form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <input type="submit" value="Importar" class="acao btn btn-primary" />
                </div>
            </div>
        </div>
    </section>

    <div id="janela_cpf" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
                    <h4 id="myModalLabel" class="modal-title">Adicionar Funcionário - Informe o C.P.F.</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="jan_cpf">C.P.F.:</label>
                        <input type="text" name="jan_cpf" id="jan_cpf" class="cpf form-control" />
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
                    <button class="btn btn-primary" id="bt_jan_procurar">Procurar</button>
                </div>
            </div>
        </div>
    </div>

    <div id="janela_ponto" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
                    <h4 id="myModalLabel" class="modal-title">Selecione o Mês</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="ano_mes">Mês:</label>
                        <select name="ano_mes" id="ano_mes" class="form-control">
                            <?php
                            $data = new Zend_Date();
                            for ($i = 6; $i >= 1; $i--) {
                                $k = $data->get("M");
                                $mes = Escola_Util::pegaMes($k);
                                $selected = "";
                                ?>
                                <option value="<?php echo $data->get("YYYY"); ?>_<?php echo $k; ?>" <?php echo $selected; ?>><?php echo $mes; ?> / <?php echo $data->get("YYYY"); ?></option>
                                <?php $data->sub('1', Zend_Date::MONTH);
                            } ?>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
                    <input type="button" value="IMPRIMIR" class="btn btn-primary" id="bt_imprimir" />
                </div>
            </div>
        </div>
    </div>
</form>
    <section class="panel">
    <header class="panel-heading">Funcionários</header>
        <input type="hidden" name="ponto_id_funcionario" id="ponto_id_funcionario" value="" />
        <table class="table table-striped table-hover table-vcenter text-sm">
            <thead>
            <tr>
                <th width="150px">C.P.F.</th>
                <th>Nome</th>
                <th>Matrícula</th>
                <th>Cargo</th>
                <th>Lotação Principal</th>
                <th>Situação</th>
                <th width="30%" class="text-right">Operações</th>
            </tr>
            </thead>
            <?php if ($this->registros && count($this->registros)) { ?>
                <tbody>
                <?php
                $tb = new TbFuncionario();
                foreach ($this->registros as $registro) {
                    $registro = $tb->getPorId($registro["id_funcionario"]);
                    $setor = "--";
                    $pf = $registro->findParentRow("TbPessoaFisica");
                    $lotacao = $registro->pegaLotacaoPrincipal();
                    if ($lotacao) {
                        $setor = $lotacao->findParentRow("TbSetor")->toString();
                    }
                    $vinculo = $registro->findParentRow("TbFuncionarioTipo");
                    $funcionario_tipo = "";
                    if ($vinculo) {
                        $funcionario_tipo = $vinculo->toString();
                    }
                    ?>
                    <tr>
                        <td>
                            <a href="<?php
                            echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "view",
                                "id" => $registro->getId()));
                            ?>" title="Visualizar">
                                <?php echo $this->formatCpf($pf->cpf); ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php
                            echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "view",
                                "id" => $registro->getId()));
                            ?>" title="Visualizar">
                                <?php echo $pf->nome; ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php
                            echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "view",
                                "id" => $registro->getId()));
                            ?>" title="Visualizar">
                                <?php echo $registro->matricula; ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php
                            echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "view",
                                "id" => $registro->getId()));
                            ?>" title="Visualizar">
                                <?php echo $registro->findParentRow("TbCargo")->toString(); ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php
                            echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "view",
                                "id" => $registro->getId()));
                            ?>" title="Visualizar">
                                <?php echo $setor; ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php
                            echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "view",
                                "id" => $registro->getId()));
                            ?>" title="Visualizar">
                                <?php echo $registro->mostrarSituacao(); ?>
                            </a>
                        </td>
                        <td>
                            <div class="btn-group pull-right">
                                <a class="btn btn-white" data-container="body" href="<?php
                                echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                    "action" => "view",
                                    "id" => $registro->getId()));
                                ?>" data-toggle="tooltip" title="Visualizar">
                                    <i class="icon-zoom-in"></i>
                                </a>
                                <a class="btn btn-white" data-container="body" href="<?php
                                echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                    "action" => "addfuncionario",
                                    "id_funcionario" => $registro->getId()));
                                ?>" data-toggle="tooltip" title="Alterar">
                                    <i class="icon-cog"></i>
                                </a>

                                <a class="btn btn-white" data-container="body" href="<?php
                                echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                    "action" => "lotacao",
                                    "id" => $registro->getId()));
                                ?>" data-toggle="tooltip" title="Lotações">
                                    <i class="icon-home icon-white"></i>
                                </a>
                                <a class="btn btn-white" data-container="body" href="<?php
                                echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                    "action" => "arquivo",
                                    "id" => $registro->getId()));
                                ?>" data-toggle="tooltip" title="Arquivos">
                                    <i class="icon-folder-open"></i>
                                </a>
                                <a class="btn btn-white" data-container="body" href="<?php
                                echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                    "action" => "ocorrencia",
                                    "id" => $registro->getId()));
                                ?>" data-toggle="tooltip" title="Ocorrências">
                                    <i class="icon-calendar"></i>
                                </a>
                                <?php if ($registro->ativo()) { ?>
                                    <a class="btn btn-white" data-container="body" href="#" id="<?php echo $registro->getId(); ?>" class="link_ponto" title="Folha de Ponto">
                                        <i class="icon-time"></i>
                                    </a>
                                <?php } ?>
                                <a class="btn btn-danger" data-container="body" href="<?php
                                echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                    "action" => "excluir",
                                    "id" => $registro->getId()));
                                ?>" class="link_excluir" title="Excluir">
                                    <i class="icon-trash"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            <?php } ?>
        </table>
    <div class="panel-footer">
        <?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
    </div>
</section>

