<section class="panel">
    <header class="panel-heading">Lotação Funcionário: <?php echo $this->funcionario->toString(); ?></header>
    <table class="table table-striped table-hover table-vcenter">
        <thead>
        <tr>
            <th>Setor</th>
            <th>Tipo</th>
            <th>Função</th>
            <th>Data Inicial</th>
            <th>Data Final</th>
            <th>Chefe</th>
            <th colspan="5" class="text-right">Operações</th>
        </tr>
        </thead>
        <?php if ($this->registros && count($this->registros)) { ?>
            <tbody>
            <?php
            foreach ($this->registros as $registro) {
                $funcionario_funcao = "";
                $funcionario = $registro->findParentRow("TbFuncionario");
                $ff = $registro->findParentRow("TbFuncionarioFuncao");
                if ($ff) {
                    $funcionario_funcao = $ff->toString();
                }
                ?>
                <tr>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewlotacao", "id_lotacao" => $registro->getId())); ?>">
                            <?php echo $registro->findParentRow("TbSetor")->toString(); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewlotacao", "id_lotacao" => $registro->getId())); ?>">
                            <?php echo $registro->findParentRow("TbLotacaoTipo")->toString(); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewlotacao", "id_lotacao" => $registro->getId())); ?>">
                            <?php echo $funcionario_funcao; ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewlotacao", "id_lotacao" => $registro->getId())); ?>">
                            <?php echo $this->formatData($registro->data_inicial); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewlotacao", "id_lotacao" => $registro->getId())); ?>">
                            <?php echo $this->formatData($registro->data_final); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewlotacao", "id_lotacao" => $registro->getId())); ?>">
                            <?php echo $registro->mostrarChefe(); ?>
                        </a>
                    </td>
                    <td>
                        <div class="btn-group pull-right">
                            <a class="btn btn-white" data-container="body" data-toggle="tooltip" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "viewlotacao",
                                "id_lotacao" => $registro->getId())); ?>" title="Visualizar">
                                <i class="icon-search"></i>
                            </a>
                            <a class="btn btn-white" data-container="body" data-toggle="tooltip" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "editarlotacao",
                                "id_lotacao" => $registro->getId())); ?>" title="Editar">
                                <i class="icon-cog"></i>
                            </a>
                            <a class="btn btn-danger" data-container="body" data-toggle="tooltip" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "excluirlotacao",
                                "id_lotacao" => $registro->getId())); ?>" class="link_excluir" title="Excluir">
                                <i class="icon-trash"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        <?php } ?>
    </table>
</section>