<section class="panel">
    <header class="panel-heading">Ocorrencia: Funcionário - <?php echo $this->funcionario->toString(); ?></header>

            <table class="table table-striped table-condensed table-hover table-vcenter">
                <thead>
                <tr>
                    <th>Tipo</th>
                    <th>Data Inicial</th>
                    <th>Data Final</th>
                    <th>Observações</th>
                    <th width="20%" class="text-right">Operações</th>
                </tr>
                </thead>
                <?php if ($this->registros && count($this->registros)) { ?>
                    <tbody>
                    <?php
                    foreach ($this->registros as $registro) {
                        $funcionario = $registro->findParentRow("TbFuncionario");
                        ?>
                        <tr>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewocorrencia", "id_funcionario_ocorrencia" => $registro->getId())); ?>">
                                    <?php echo $registro->findParentRow("TbFuncionarioOcorrenciaTipo")->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewocorrencia", "id_funcionario_ocorrencia" => $registro->getId())); ?>">
                                    <?php echo Escola_Util::formatData($registro->data_inicio); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewocorrencia", "id_funcionario_ocorrencia" => $registro->getId())); ?>">
                                    <?php echo Escola_Util::formatData($registro->data_final); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewocorrencia", "id_funcionario_ocorrencia" => $registro->getId())); ?>">
                                    <?php echo $registro->observacoes; ?>
                                </a>
                            </td>
                            <td>
                                <div class="btn-group pull-right">
                                    <a class="btn btn-white" data-container="body" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                        "action" => "viewocorrencia",
                                        "id_funcionario_ocorrencia" => $registro->getId())); ?>" data-toggle="tooltip" title="Visualizar">
                                        <i class="icon-search"></i>
                                    </a>
                                    <a class="btn btn-white" data-container="body" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                        "action" => "editarocorrencia",
                                        "id_funcionario_ocorrencia" => $registro->getId())); ?>" data-toggle="tooltip" title="Editar">
                                        <i class="icon-cog"></i>
                                    </a>
                                    <a class="btn btn-danger" data-container="body" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                        "action" => "excluirocorrencia",
                                        "id_funcionario_ocorrencia" => $registro->getId())); ?>" class="link_excluir" data-toggle="tooltip" title="Excluir">
                                        <i class="icon-trash"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                <?php } ?>
            </table>
</section>