<section class="panel">
    <header class="panel-heading">Tipo de Chamado: <?php echo $this->chamado_tipo->toString(); ?></header>

        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "setorsalvar")); ?>" method="post" id="formulario" class="formulario form-horizontal">
            <input type="hidden" name="id" id="id" value="<?php echo $this->chamado_tipo->getId(); ?>" />
            <input type="hidden" name="jan_pagina" id="jan_pagina" />
            <input type="hidden" name="operacao" id="operacao" value="" />
            <input type="hidden" name="id_setor" id="id_setor" value="" />

            <div id="janela_setor" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h3 class="modal-title" id="myModalLabel">Localizar Setor</h3>
                        </div>
                        <div class="modal-body">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="jan_setor_criterio">Procurar Por:</label>
                                    <input type="text" name="jan_setor_criterio" id="jan_setor_criterio" value="" class="form-control" />
                                </div>
                            </div>
                            <table id="lista_setor_resposta" class="table table-striped table-bordered">
                                <thead>
                                <th width="50px">ID</th>
                                <th width="160px">Sigla</th>
                                <th>Descrição</th>
                                </thead>
                                <tbody class="corpo_setor"></tbody>
                            </table>
                        </div>
                        <div class="modal-footer">
                            <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
                            <input type="button" value="Limpar Filtro" id="bt_setor_limpar" class="btn" />
                            <input type="submit" value="Procurar" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </div>


            <?php //echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
        </form>
    <table class="table table-striped table-condensed table-hover">
        <thead>
        <tr>
            <th>Sigla</th>
            <th>Descrição</th>
            <th class="text-right" 20px">Operações</th clA20px">
        </tr>
        </thead>
        <?php if ($this->registros && count($this->registros)) { ?>
            <tbody>
            <?php
            foreach ($this->registros as $registro) {
                ?>
                <tr>
                    <td>
                        <?php echo $registro->sigla; ?>
                    </td>
                    <td>
                        <?php echo $registro->descricao; ?>
                    </td>
                    <td>
                        <div class="btn-group pull-right">
                            <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "excluirsetor",
                                "id_setor" => $registro->getId())); ?>" class="btn btn-danger link_excluir" data-toggle="tooltip" data-container="body" title="Excluir">
                                <i class="icon-trash"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        <?php } ?>
    </table>
</section>