<section class="panel">
    <header class="panel-heading">
        Visualizar Tipo de Ítem de Boleto
    </header>
    <div class="panel-body">
        <dl class="dl-horizontal">
                    <dt>Código:</dt>
                    <dd><?php echo $this->registro->getId(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Chave:</dt>
                    <dd><?php echo $this->registro->chave; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Descrição:</dt>
                    <dd><?php echo $this->registro->descricao; ?></dd>
                </dl>
    </div>
</section>