version: "3"
services:
  intranet_sttrans_db:
    image: mariadb
    container_name: intranet_sttrans_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: s0laris
    volumes:
      - "./volumes/mysql/intranet:/var/lib/mysql"
      - "./intranet_sttrans.sql:/docker-entrypoint-initdb.d/intranet_sttrans.sql"

  intranet_sttrans_db_log:
    image: mariadb
    container_name: intranet_sttrans_db_log
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: s0laris
    volumes:
      - "./volumes/mysql/intranet_db:/var/lib/mysql"
      - "./intranet_sttrans_log.sql:/docker-entrypoint-initdb.d/intranet_sttrans_log.sql"

  intranet_sttrans_site:
    build:
      context: .
      dockerfile: intranet.dockerfile
    image: intranet_sttrans_site
    container_name: intranet_sttrans_site
    restart: always
    volumes:
      - ./html:/var/www/html
    depends_on:
      - intranet_sttrans_db
      - intranet_sttrans_db_log

  intranet_sttrans_nginx:
    build:
      dockerfile: ./nginx.dockerfile
      context: .
    image: intranet_sttrans_nginx
    container_name: intranet_sttrans_nginx
    ports:
      - 80:80
    volumes:
      - ./html/public/css:/var/www/public/css
      - ./html/public/js:/var/www/public/js
      - ./html/public/img:/var/www/public/img
    depends_on:
      - intranet_sttrans_site
