version: "3"
services:
  intranet_sttrans_db:
    image: mariadb
    container_name: intranet_sttrans_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: s0laris
    ports:
      - "3307:3306"
    volumes:
      - "./volumes/mysql/intranet:/var/lib/mysql"
      - "./intranet_sttrans.sql:/docker-entrypoint-initdb.d/intranet_sttrans.sql"

  intranet_sttrans_db_legado:
    image: mariadb
    container_name: intranet_sttrans_db_legado
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: s0laris
    ports:
      - "3308:3306"
    volumes:
      - "./volumes/mysql/intranet_legado:/var/lib/mysql"
      - "./intranet_sttrans_legado.sql:/docker-entrypoint-initdb.d/intranet_sttrans.sql"

  intranet_sttrans_db_log:
    image: mariadb
    container_name: intranet_sttrans_db_log
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: s0laris
    volumes:
      - "./volumes/mysql/intranet_db:/var/lib/mysql"
      - "./intranet_sttrans_log.sql:/docker-entrypoint-initdb.d/intranet_sttrans_log.sql"

  intranet_sttrans_site:
    build:
      context: .
      dockerfile: intranet.dockerfile
    image: intranet_sttrans_site
    container_name: intranet_sttrans_site
    restart: always
    ports:
      - 8087:80
    volumes:
      - ./html_sttrans:/var/www/html
    depends_on:
      - intranet_sttrans_db
      - intranet_sttrans_db_log
