

<?php
if ($this->pageCount > 1): ?>
<ul class="pagination pagination-sm m-t-none m-b-none">

	<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
	<li><a href="<?php echo $this->url(array('page' => $this->previous)); ?>"><i class="icon-double-angle-left"></i></a></li>
<?php else: ?>
	<li class="disabled"><a href="#"><i class="icon-angle-left"></i> </a></li>
<?php endif; ?>
 
	<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
  	<li><a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a></li>
  <?php else: ?>
    <li class="disabled active"><a href="#"><?php echo $page; ?></a></li>
  <?php endif; ?>
<?php endforeach; ?>
 
	<!-- Next page link -->
<?php if (isset($this->next)): ?>
	<li><a href="<?php echo $this->url(array('page' => $this->next)); ?>"><i class="icon-double-angle-right"></i></a></li>
<?php else: ?>
	<li class="disabled"><a href="#"><i class="icon-angle-right"></i></a></li>
<?php endif; ?>

</ul>
<?php endif; ?>