<?php
$valor_a_pagar = $this->stg->findParentRow("TbValor");
$tb = new TbMoeda();
$moeda = $tb->pega_padrao();
?>
<section class="panel">
    <header class="panel-heading">CONFIRMAR PAGAMENTO DE SERVIÇO</header>
    <div class="panel-body">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "licencapgto")); ?>" method="post" id="formulario" class="formulario">
            <input type="hidden" name="id_servico_solicitacao" id="id_servico_solicitacao" value="<?php echo $this->registro->getId(); ?>" />
            <dl class="dl-horizontal">
                <dt>Motorista:</dt>
                <dd><?php echo $this->motorista->toString(); ?></dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>Serviço:</dt>
                <dd><?php echo $this->stg->findParentRow("TbServico")->toString(); ?></dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>Referência:</dt>
                <dd><?php echo $this->registro->mostrar_referencia(); ?></dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>Valor:</dt>
                <dd><?php echo $valor_a_pagar->toString(); ?></dd>
            </dl>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="data_pagamento" class="control-label">Data Pagamento:</label>
                    <input type="text" name="data_pagamento" id="data_pagamento" class="form-control data" value="<?php echo date("d/m/Y"); ?>" />
                </div>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Valor("valor_pago");
                $ctrl->setLabel("Valor Pago:");
                $ctrl->setValue($valor_a_pagar->valor);
                $ctrl->setAttrib('class', 'form-control');
                if ($moeda) {
                    $ctrl->set_moeda($moeda);
                }
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Valor("valor_juros");
                $ctrl->setLabel("Juros:");
                $ctrl->setValue(0);
                $ctrl->setAttrib('class', 'form-control');
                if ($moeda) {
                    $ctrl->set_moeda($moeda);
                }
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Valor("valor_desconto");
                $ctrl->setLabel("Desconto:");
                $ctrl->setValue(0);
                $ctrl->setAttrib('class', 'form-control');
                if ($moeda) {
                    $ctrl->set_moeda($moeda);
                }
                echo $ctrl->render($this);
                ?>
            </div>
        </form>
    </div>
</section>