<section class="panel">
    <header class="panel-heading">Relatórios Vinculados ao Motorista</header>
    <div class="panel-body">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => $this->getRequest()->getActionName())); ?>" method="post" id="formulario" class="formulario" enctype="multipart/form-data">
            <input type="hidden" name="operacao" id="operacao" value="imprimir" />
            <dl class="dl-horizontal">
                <dt>Motorista:</dt>
                <dd><?php echo $this->motorista->toString(); ?></dd>
            </dl>
            <div class="col-md-4">
            <div class="form-group">
                <label for="tipo" class="control-label">Relatório(s):</label>
                <select name="id_relatorio" id="id_relatorio" class="form-control">
                    <option value="" <?php echo (!$this->dados["id_relatorio"])?"selected":""; ?>>==> SELECIONE UM RELATÓRIO <==</option>
                    <?php foreach ($this->relatorios as $relatorio) { ?>
                        <option value="<?php echo $relatorio->getId(); ?>" <?php echo ($this->dados["id_relatorio"] == $relatorio->getId())?"selected":""; ?>><?php echo $relatorio->toString(); ?></option>
                    <?php } ?>
                </select>
            </div>
            </div>
            <div class="col-md-4">
            <div class="form-group">
                <label for="tipo" class="control-label">Tipo de Saída:</label>
                <select name="tipo" id="tipo" class="form-control">
                    <option value="HTML" <?php echo ($this->dados["tipo"] == "HTML")?"selected":""; ?>>VISUALIZAR</option>
                    <option value="PDF" <?php echo ($this->dados["tipo"] == "PDF")?"selected":""; ?>>PDF</option>
                </select>
            </div>
            </div>
            <?php
            if (!$this->errors && $this->rel && $this->method) {
                $method = $this->method;
                echo $this->rel->$method();
            }
            ?>
        </form>
    </div>
</section>