<section class="panel"  id="idPesquisa" style="display:none;">
    <header class="panel-heading">
        Opções de Pesquisa
    </header>
    <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => $this->getRequest()->getActionName())); ?>" method="post" id="formulario" class="formulario">
    <div class="panel-body">
        <div class="col-md-4">
            <div class="form-group">
                <label for="filtro_titulo">Título:</label>
                <input type="text" name="filtro_titulo" id="filtro_titulo" class="form-control filtro" value="<?php echo $this->dados["filtro_titulo"]; ?>" />
            </div>
        </div>
        <div class="col-md-4">
            <?php
            $ctrl = new Escola_Form_Element_Select_Table("filtro_id_pessoa_tipo");
            $ctrl->setAttrib("class", "filtro");
            $ctrl->setPkName("id_pessoa_tipo");
            $ctrl->setModel("TbPessoaTipo");
            $ctrl->setValue($this->dados["filtro_id_pessoa_tipo"]);
            $ctrl->setLabel("Tipo de Pessoa:");
            $ctrl->setAttrib('class', 'form-control');
            echo $ctrl->render($this);
            ?>
        </div>
        <div class="col-md-4 linha_cpf">
            <div class="form-group">
                <label for="filtro_cpf">C.P.F.:</label>
                <input type="text" name="filtro_cpf" id="filtro_cpf" class="form-control cpf filtro" value="<?php echo $this->dados["filtro_cpf"]; ?>" />
            </div>
        </div>
        <div class="col-md-4 linha_cnpj">
            <div class="form-group">
                <label for="filtro_cnpj">C.N.P.J.:</label>
                <input type="text" name="filtro_cnpj" id="filtro_cnpj" class="form-control cnpj filtro" value="<?php echo $this->dados["filtro_cnpj"]; ?>" />
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="filtro_nome">Nome:</label>
                <input type="text" name="filtro_nome" id="filtro_nome" class="form-control filtro" value="<?php echo $this->dados["filtro_nome"]; ?>" />
            </div>
        </div>
        <div class="col-md-4">
            <?php
            $ctrl = new Escola_Form_Element_Select_Table("filtro_id_servico_solicitacao_status");
            $ctrl->setAttrib("class", "filtro");
            $ctrl->setPkName("id_servico_solicitacao_status");
            $ctrl->setModel("TbServicoSolicitacaoStatus");
            $ctrl->setValue($this->dados["filtro_id_servico_solicitacao_status"]);
            $ctrl->setLabel("Status:");
            $ctrl->setAttrib('class', 'form-control');
            echo $ctrl->render($this);
            ?>
        </div>
    </div>
    <div class="panel-footer">
        <input type="submit" value="Pesquisar" class="acao btn btn-primary" />
        <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />
    </div>
    </form>
</section>

<section class="panel">
    <header class="panel-heading">
        Serviço: <?php echo $this->servico->toString(); ?>
    </header>
    <table class="table table-striped table-condensed table-hover">
        <thead>
        <tr>
            <th>Título</th>
            <th>Pessoa</th>
            <th>Número/Ano</th>
            <th>Referência</th>
            <th>Data Solicitação</th>
            <th>Vencimento</th>
            <th>Valor</th>
            <th>Valor Pago</th>
            <th>Início</th>
            <th>Validade</th>
            <th>Status</th>
            <th width="20%" class="text-right">Operações</th>
        </tr>
        </thead>
        <?php if ($this->registros && count($this->registros)) { ?>
            <tbody>
            <?php
            foreach ($this->registros as $registro) {
                $ss = $registro->pegaSolicitacao();
                $pessoa = $registro->findParentRow("TbPessoa");
                $ssp = $ss->pegaPagamento();
                ?>
                <tr>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo $registro->titulo; ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo $pessoa->toString(); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo $ss->mostrar_numero(); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo $ss->mostrar_referencia(); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo Escola_Util::formatData($ss->data_solicitacao); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo Escola_Util::formatData($ss->data_vencimento); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo $ss->pega_valor()->toString(); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo ($ssp) ? $ssp->pega_valor_pago()->toString() : "--"; ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo Escola_Util::formatData($ss->data_inicio); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo Escola_Util::formatData($ss->data_validade); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo $ss->mostrarStatusHTML(); ?>
                        </a>
                    </td>
                    <td>
                        <div class="btn-group pull-right">
                            <a href="<?php
                            echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "view",
                                "id" => $registro->getId()));
                            ?>" class="btn btn-white" data-toggle="tooltip" data-container="body"  title="Visualizar">
                                <i class="icon-search"></i>
                            </a>
                            <a href="<?php
                            echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "editar",
                                "id" => $registro->getId()));
                            ?>" class="btn btn-white" data-toggle="tooltip" data-container="body"  title="Editar">
                                <i class="icon-cog"></i>
                            </a>
                            <?php if ($ss->pago()) { ?>
                                <a href="<?php
                                echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                    "action" => "emitir",
                                    "id" => $registro->getId()));
                                ?>" class="btn btn-white" data-toggle="tooltip" data-container="body"  title="Emitir Documento">
                                    <i class="icon-print"></i>
                                </a>
                            <?php } else { ?>
                                <a target="_blank" href="<?php
                                echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                    "action" => "boleto",
                                    "id" => $registro->getId()));
                                ?>" class="btn btn-white" data-toggle="tooltip" data-container="body"  title="Gerar Boleto">
                                    <i class="icon-credit-card"></i>
                                </a>
                                <a href="<?php
                                echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                    "action" => "licencapgto",
                                    "id" => $registro->getId()));
                                ?>" class="btn btn-white" data-toggle="tooltip" data-container="body"  title="Confirmar Pagamento">
                                    <i class="icon-money"></i>
                                </a>
                                <a href="<?php
                                echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                    "action" => "excluir",
                                    "id" => $registro->getId()));
                                ?>" class="btn btn-danger link_excluir"  data-toggle="tooltip" data-container="body" title="Excluir">
                                    <i class="icon-trash"></i>
                                </a>
                            <?php } ?>
                        </div>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        <?php } ?>
    </table>
    <div class="panel-footer">
        <?php
        if ($this->registros && count($this->registros)) {
            echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml");
        }
        ?>
    </div>
</section>