<section class="panel">
    <header class="panel-heading">
        Cadastro de Banco
    </header>
    <div class="panel-body">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "editar")); ?>" method="post" id="formulario" class="formulario">
            <input type="hidden" name="id" id="id" value="<?php echo $this->registro->getId(); ?>" />
            <?php if ($this->registro->getId()) { ?>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="codigo">Código:</label>
                        <input type="text" name="codigo" id="codigo" maxlength="10" value="<?php echo $this->registro->getId(); ?>" class="form-control" disabled/>
                    </div>
                </div>
            <?php } ?>
            <div class="col-md-4">
            <div class="form-group">
                <label for="codigo">Código:</label>
                <input type="text" name="codigo" id="codigo" class="form-control" value="<?php echo $this->registro->codigo; ?>" maxlength="5" />
            </div>
            </div>
            <div class="col-md-4">
            <div class="form-group">
                <label for="sigla">Sigla:</label>
                <input type="text" name="sigla" id="sigla" class="form-control" value="<?php echo $this->registro->sigla; ?>" maxlength="20" />
            </div>
            </div>
            <div class="col-md-4">
            <div class="form-group">
                <label for="descricao">Descrição:</label>
                <input type="text" name="descricao" id="descricao" class="form-control" value="<?php echo $this->registro->descricao; ?>" maxlength="100" />
            </div>
            </div>
    </div>
</section>