<section class="panel">
    <header class="panel-heading">
        Lista de Bancos
    </header>
    <table class="table table-striped table-condensed table-hover">
        <thead>
        <tr>
            <th>Código</th>
            <th>Sigla</th>
            <th>Descrição</th>
            <th width="20%">Operações</th>
        </tr>
        </thead>
        <?php if ($this->registros && count($this->registros)) { ?>
            <tbody>
            <?php
            foreach ($this->registros as $registro) {
                ?>
                <tr>
                    <td>
                        <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                            "action" => "view",
                            "id" => $registro->getId())); ?>" title="Visualizar">
                            <?php echo $registro->codigo; ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                            "action" => "view",
                            "id" => $registro->getId())); ?>" title="Visualizar">
                            <?php echo $registro->sigla; ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                            "action" => "view",
                            "id" => $registro->getId())); ?>" title="Visualizar">
                            <?php echo $registro->descricao; ?>
                        </a>
                    </td>

                    <td>
                        <div class="btn-group pull-right">
                            <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "view",
                                "id" => $registro->getId())); ?>" class="btn btn-white" data-toggle="tooltip" data-container="body" data-toggle="tooltip" title="Visualizar">
                                <i class="icon-zoom-in"></i>
                            </a>
                            <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "editar",
                                "id" => $registro->getId())); ?>" class="btn btn-white" data-toggle="tooltip" data-container="body" title="Alterar">
                                <i class="icon-cog"></i>
                            </a>
                            <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "excluir",
                                "id" => $registro->getId())); ?>" class="btn btn-danger link_excluir" data-toggle="tooltip" data-container="body" title="Excluir">
                                <i class="icon-trash"></i>
                            </a>

                        </div>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        <?php } ?>
    </table>
    <div class="panel-footer">
        <?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
    </div>
</section>