<section class="panel">
    <header class="panel-heading">
        Visualizar Banco
    </header>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>ID:</dt>
            <dd><?php echo $this->registro->getId(); ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Código:</dt>
            <dd><?php echo $this->registro->codigo; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Sigla:</dt>
            <dd><?php echo $this->registro->sigla; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Descrição:</dt>
            <dd><?php echo $this->registro->descricao; ?></dd>
        </dl>
    </div>
</section>