<section class="panel">
    <header class="panel-heading">
        Pacote
    </header>
    <div class="panel-body">
        <form action="<?php echo $this->url(array("action" => "editar")); ?>" method="post" id="formulario" class="formulario">
            <input type="hidden" name="id" id="id" value="<?php echo $this->registro->getId(); ?>" />
        <div class="row">
        <?php if ($this->registro->getId()) { ?>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="descricao">Código:</label>
                    <input type="text" value="<?php echo $this->registro->getId(); ?>"   class="form-control" disabled />
                </div>
            </div>
        <?php } ?>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="sigla">Sigla.:</label>
                    <input type="text" name="sigla" id="sigla" maxlength="10" value="<?php echo $this->registro->sigla; ?>" class="form-control" />   
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="descricao">Descrição.:</label>
                    <input type="text" name="descricao" id="descricao" maxlength="60" value="<?php echo $this->registro->descricao; ?>" class="form-control" />    
                </div>
            </div>
            <div class="col-md-4">
                <?php
                    $ctrl = new Escola_Form_Element_Icone("icone");
                    $ctrl->setAttrib("id", "pacote_icone");
                    $ctrl->setValue($this->registro->icone);
                    echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="resumo">Status:</label>                
                    <select class="form-control" name="status" id="status">
                        <option value="A" <?php echo ($this->registro->ativo())?"selected":""; ?>>ATIVO</option>
                        <option value="I" <?php echo ($this->registro->inativo())?"selected":""; ?>>INATIVO</option>                                                            
                    </select>
                </div>
            </div>
        <?php if ($this->ultima_ordem) { ?>
            <div class="col-md-4">
                <div class="form-group">
                <label for="ordem">Ordem:</label>
                    <select class="form-control" name="ordem" id="ordem">
                    <option value="" <?php echo (!$this->registro->ordem)?"selected":""; ?>>==> SELECIONE <==</option>
                    <?php for ($i = 1; $i <= $this->ultima_ordem; $i++) { ?>
                    <option value="<?php echo $i; ?>" <?php echo ($i == $this->registro->ordem)?"selected":""; ?>><?php echo $i; ?></option>
                    <?php } ?>
                    </select>
                </div>
            </div>
        <?php } ?>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="resumo">Resumo:</label>
                    <textarea name="resumo" id="resumo" rows="6" class="form-control"><?php echo $this->registro->resumo; ?></textarea>
                </div>
            </div>
        </div>
        </form>
    </div>
    <div class="panel-footer">
        
    </div>
</section>