<section class="panel">
    <header class="panel-heading">Transporte: <?php echo $this->transporte->toString(); ?></header>
    <table class="table table-striped table-condensed table-hover">
        <thead>
        <tr>
            <th>Miniatura</th>
            <th>Data Envio</th>
            <th>Tamanho</th>
            <th>Tipo</th>
            <th>Tipo Documento</th>
            <th>Número</th>
            <th>Descrição</th>
            <th width="20%" class="text-right">Operações</th>
        </tr>
        </thead>
        <?php if ($this->registros && count($this->registros)) { ?>
            <tbody>
            <?php
            foreach ($this->registros as $registro) {
                $documento = $registro->findParentRow("TbDocumento");
                $arquivo = $documento->pega_arquivo();
                $dt = $documento->findParentRow("TbDocumentoTipo");
                ?>
                <tr>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewarquivo", "id_documento_ref" => $registro->getId())); ?>">
                            <?php echo $arquivo->miniatura(array("width" => 50, "align" => "left")); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewarquivo", "id_documento_ref" => $registro->getId())); ?>">
                            <?php echo Escola_Util::formatData($arquivo->data_upload); ?> <?php echo $arquivo->hora_upload; ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewarquivo", "id_documento_ref" => $registro->getId())); ?>">
                            <?php echo Escola_Util::mostrarTamanho($arquivo->tamanho); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewarquivo", "id_documento_ref" => $registro->getId())); ?>">
                            <?php echo $dt->findParentRow("TbDocumentoTipoTarget")->toString(); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewarquivo", "id_documento_ref" => $registro->getId())); ?>">
                            <?php echo $dt->toString(); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewarquivo", "id_documento_ref" => $registro->getId())); ?>">
                            <?php echo $documento->mostrarNumero(); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewarquivo", "id_documento_ref" => $registro->getId())); ?>">
                            <?php echo $documento->resumo; ?>
                        </a>
                    </td>
                    <td>
                        <div class="btn-group">
                            <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "viewarquivo",
                                "id_documento_ref" => $registro->getId())); ?>" class="btn btn-white" data-toggle="tooltip" data-container="body" title="Visualizar">
                                <i class="icon-search"></i>
                            </a>
                            <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "editararquivo",
                                "id_documento_ref" => $registro->getId())); ?>"  data-toggle="tooltip" data-container="body" class="btn btn-white" title="Editar">
                                <i class="icon-cog"></i>
                            </a>
                            <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "excluirarquivo",
                                "id_documento_ref" => $registro->getId())); ?>" class="btn btn-danger link_excluir" data-toggle="tooltip" data-container="body" title="Excluir">
                                <i class="icon-trash"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        <?php } ?>
    </table>
    <div class="panel-footer">
        <?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
    </div>
</section>