<section class="panel">
    <header class="panel-heading">CADASTRO DE TRANSPORTE > PESSOA</header>
    <div class="panel-body">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "editarpessoa")); ?>" method="post" id="formulario" class="formulario">
            <input type="hidden" name="id" id="id" value="<?php echo $this->registro->getId(); ?>" />
            <input type="hidden" name="id_transporte" id="id_transporte" value="<?php echo $this->transporte->getId(); ?>" />
            <?php if ($this->registro->getId()) { ?>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="codigo">Código:</label>
                        <input type="text" name="codigo" id="codigo" maxlength="10" value="<?php echo $this->registro->getId(); ?>" class="form-control" disabled/>
                    </div>
                </div>
            <?php } ?>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="Transporte">Transporte:</label>
                    <input type="text" name="Transporte" id="Transporte" maxlength="10" value="<?php echo $this->transporte->toString(); ?>" class="form-control" disabled/>
                </div>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table("id_transporte_pessoa_tipo");
                $ctrl->setPkName("id_transporte_pessoa_tipo");
                $ctrl->setModel("TbTransportePessoaTipo");
                $ctrl->setValue($this->registro->id_transporte_pessoa_tipo);
                $ctrl->setLabel("Tipo: ");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table_Pessoa("id_pessoa");
                $ctrl->setValue($this->registro->id_pessoa);
                $ctrl->setLabel("Pessoa: ");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table_Motorista("id_motorista");
                $ctrl->setValue($this->registro->id_motorista);
                $ctrl->setLabel("Motorista: ");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
        </form>
    </div>
</section>