<section class="panel">
    <header class="panel-heading">
        Relatórios
    </header>
    <div class="panel-body">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => $this->getRequest()->getActionName())); ?>" method="post" id="formulario" class="formulario form-horizontal" enctype="multipart/form-data">
            <input type="hidden" name="operacao" id="operacao" value="imprimir" />
            <input type="hidden" name="tipo" id="tipo" value="PDF" />
            <input type="hidden" name="id" id="id" value="<?php echo $this->transporte->getId(); ?>" />
            <dl class="dl-horizontal">
                <dt>Transporte:</dt>
                <dd><?php echo $this->transporte->toString(); ?></dd>
            </dl>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="id_relatorio">Relatório:</label>
                    <select name="id_relatorio" id="id_relatorio" class="form-control">
                        <option value="" <?php echo (!$this->dados["id_relatorio"]) ? "selected" : ""; ?>>==> SELECIONE <==</option>
                        <?php foreach ($this->relatorios as $relatorio) { ?>
                            <option value="<?php echo $relatorio->getId(); ?>" <?php echo ($relatorio->getId() == $this->dados["id_relatorio"]) ? "selected" : ""; ?>><?php echo $relatorio->toString(); ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <?php
            if ($this->relatorio && $this->method) {
                $method = $this->method;
                echo $this->relatorio->$method();
            }
            ?>
        </form>
    </div>
</section>