<section class="panel">
    <header class="panel-heading">CADASTRO DE SERVÇOS</header>
    <div class="panel-body">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "editar")); ?>" method="post" id="formulario" class="formulario">
            <input type="hidden" name="id" id="id" value="<?php echo $this->registro->getId(); ?>" />
            <?php if ($this->registro->getId()) { ?>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="codigo">Código:</label>
                        <input type="text" name="codigo" id="codigo" maxlength="60" value="<?php echo $this->registro->getId(); ?>" class="form-control" disabled/>
                    </div>
                </div>
            <?php } ?>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table("id_servico_tipo");
                $ctrl->setPkName("id_servico_tipo");
                $ctrl->setModel("TbServicoTipo");
                $ctrl->setValue($this->registro->id_servico_tipo);
                $ctrl->setLabel("Tipo: ");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="descricao">Código:</label>
                    <input type="text" name="codigo" id="codigo" maxlength="10" value="<?php echo $this->registro->codigo; ?>" class="form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="descricao">Descrição:</label>
                    <input type="text" name="descricao" id="descricao" maxlength="60" value="<?php echo $this->registro->descricao; ?>" class="form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table("id_servico_referencia");
                $ctrl->setPkName("id_servico_referencia");
                $ctrl->setModel("TbServicoReferencia");
                $ctrl->setValue($this->registro->id_servico_referencia);
                $ctrl->setLabel("Tipo Referência: ");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
        </form>
    </div>
</section>