<section class="panel" id="importar" class="importar" style="display:none">
    <header class="panel-heading">
        Importar Ícones
    </header>
    <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "index")); ?>" method="post" id="formulario" class="formulario form-horizontal" enctype="multipart/form-data">
    <div class="panel-footer">
        <div class="control-group">
            <label for="arquivo" class="control-label">Arquivo de Dados (CSV):</label>
            <div class="controls">
                <input type="file" name="arquivo" id="arquivo"  />
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <input type="submit" value="Importar" class="acao btn btn-primary" />
            </div>
        </div>
    </div>
    </form>
</section>

<section class="panel">
    <header class="panel-heading">
        Lista de Ícones
    </header>
    <table class="table table-striped table-condensed table-hover">
        <thead>
        <tr>
            <th>Tipo</th>
            <th>Descrição</th>
            <th width="20px"></th>
            <th width="20%" class="text-right">Operações</th>
        </tr>
        </thead>
        <?php if ($this->registros && count($this->registros)) { ?>
            <tbody>
            <?php
            foreach ($this->registros as $registro) {
                ?>
                <tr>
                    <td>
                        <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                            "action" => "view",
                            "id" => $registro->getId())); ?>" title="Visualizar">
                            <?php echo $registro->findParentRow("TbIconeTipo")->toString(); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                            "action" => "view",
                            "id" => $registro->getId())); ?>" title="Visualizar">
                            <?php echo $registro->descricao; ?>
                        </a>
                    </td>
                    <td>
                        <div align="center">
                            <i class="<?php echo $registro->descricao; ?> icon-2x"></i>
                        </div>
                    </td>
                    <td>
                        <div class="btn-group pull-right">
                            <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "view",
                                "id" => $registro->getId())); ?>" class="btn btn-white" data-toggle="tooltip" data-container="body"  data-toggle="tooltip" title="Visualizar">
                                <i class="icon-zoom-in"></i>
                            </a>
                            <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "editar",
                                "id" => $registro->getId())); ?>" class="btn btn-white" data-toggle="tooltip" data-container="body"  title="Alterar">
                                <i class="icon-cog"></i>
                            </a>
                            <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "excluir",
                                "id" => $registro->getId())); ?>" class="btn btn-danger link_excluir" data-toggle="tooltip" data-container="body"  title="Excluir">
                                <i class="icon-trash"></i>
                            </a>

                        </div>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        <?php } ?>
    </table>
    <div class="panel-footer">
        <?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
    </div>
</section>