<section class="panel">
    <header class="panel-heading">
        Visualizar Ícone
    </header>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>ID:</dt>
            <dd><?php echo $this->registro->getId(); ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Tipo:</dt>
            <dd><?php echo $this->registro->findParentRow("TbIconeTipo")->toString(); ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Descrição:</dt>
            <dd><?php echo $this->registro->descricao; ?></dd>
        </dl>
    </div>
</section>