<section class="panel">
    <header class="panel-heading">
        Módulo: <?php echo $this->modulo_atual->toString(); ?>
    </header>
    <table class="table table-striped table-hover table-vcenter">
    <thead>
        <tr>
            <th>Descrição</th>
            <th>Action</th>
            <th>Principal</th>
            <th class="text-right">Operações</th>
        </tr>
    </thead>
    <?php if ($this->acaos) { ?>
    <tbody>
    <?php foreach ($this->acaos as $acao) { ?>
        <tr>
            <td>
                <?php echo $acao->descricao; ?>
            </td>
            <td>
                <?php echo $acao->action; ?>
            </td>
            <td>
                <?php echo $acao->mostrarPrincipal(); ?>
            </td>
            <td >
                <div class="btn-group pull-right">	
                    <a class="btn btn-white" data-container="body" href="<?php echo $this->url(array("action" => "viewacao","id" => $acao->getId())); ?>" title="Visualizar" data-toggle="tooltip">
                        <i class="icon-zoom-in"></i>
                    </a>
                    <a class="btn btn-white" data-container="body" href="<?php echo $this->url(array("action" => "editaracao","id" => $acao->getId())); ?>" title="Editar"data-toggle="tooltip">
                        <i class="icon-cog"></i>
                    </a>
                    <a class="btn btn-danger" data-container="body" href="<?php echo $this->url(array("action" => "excluiracao","id" => $acao->getId())); ?>" id="ExcluirAcao" title="Excluir" class="link_excluir" data-toggle="tooltip">
                        <i class="icon-trash"></i>
                    </a>
                </div>
            </td>
        </tr>
    <?php } ?>
    </tbody>
    <?php } ?>
    </table>
    <div class="panel-footer">
        <?php echo $this->paginationControl($this->acaos, "sliding", "minha_paginacao_control.phtml"); ?>
    </div>
</section>
