<section class="panel">
    <header class="panel-heading">
	Módulo: <?php echo $this->modulo_atual->toString(); ?>
    </header>
	<div class="panel-body">
	<form action="<?php echo $this->url(array("controller" => "modulo", "action" => "editaracao")); ?>" method="post" id="formulario" class="formulario">
		<input type="hidden" name="id_modulo" id="id_modulo" value="<?php echo $this->modulo_atual->getId(); ?>" />
		<input type="hidden" name="id" id="id" value="<?php echo $this->acao_atual->getId(); ?>" />
			<div class="col-md-4">
				<div class="form-group">
					<label for="descricao" >Descrição.:</label>
					<input type="text" name="descricao" id="descricao" maxlength="60" value="<?php echo $this->acao_atual->descricao; ?>" class="form-control" />
				</div>
			</div>
			<div class="col-md-4">
				<div class="form-group">
					<label for="action" >Action:</label>
					<input type="text" name="action" id="action" maxlength="60" value="<?php echo $this->acao_atual->action; ?>" class="form-control" />
				</div>
			</div>
			<div class="col-md-4">
				<div class="form-group">
					<label for="principal" >Principal:</label>
					<select name="principal" id="principal" class="form-control">
						<option value="" <?php echo (!$this->acao_atual->principal)?"selected":""; ?> >==> SELECIONE <==</option>
						<option value="S" <?php echo ($this->acao_atual->principal == "S")?"selected":""; ?>>SIM</option>
						<option value="N" <?php echo ($this->acao_atual->principal == "N")?"selected":""; ?>>NÃO</option>
					</select>
				</div>
			</div>
	</form>
	</div>    
</section>