<form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "index")); ?>" method="post" id="formulario" class="formulario">
<section class="panel" id="idPesquisa">
    <header class="panel-heading">
        Opções de Pesquisa
    </header>
    <div class="panel-body">
        <div class="form-group">
            <label for="filtro_descricao">Descrição:</label>
            <input type="text" class="filtro form-control" name="filtro_descricao" id="filtro_descricao" value="<?php echo $this->dados["filtro_descricao"]; ?>" />
        </div>
        <div class="form-group">
            <input type="submit" value="Pesquisar" class="acao btn btn-primary" />
            <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn btn-primary" />
        </div>
    </div>
</section>
</form>
<section class="panel">
    <header class="panel-heading">
        Módulos
    </header>
    <table class="table table-striped table-hover table-vcenter text-sm">
        <thead>
            <tr>
                <th>Ordem</th>
                <th>Descrição</th>
                <th>Controller</th>
                <th>Action</th>
                <th>Módulo Superior</th>
                <th>Ícone</th>
                <th>Status</th>
                <th style="width: 30%" class="text-right">Operações</th>
            </tr>
        </thead>
        <?php if ($this->modulos) { ?>
        <tbody>
        <?php 
            foreach ($this->modulos as $modulo) { 
                $superior = "";
                $m_superior = $modulo->pegaSuperior();
                if ($m_superior) {
                        $superior = $m_superior->descricao;
                }
        ?>
        <tr>
            <td>
                <?php echo $modulo->ordem; ?>
            </td>
            <td>
                <?php echo $modulo->descricao; ?>
            </td>
            <td>
                <?php echo $modulo->controller; ?>
            </td>
            <td>
                <?php echo $modulo->action; ?>
            </td>
            <td>
                <?php echo $superior; ?>
            </td>
            <td>
                <div align="center">
                    <?php if ($modulo->icon) { ?>
                    <i class="<?php echo $modulo->icon; ?> icon-large"></i>
                    <?php } ?>
                </div>
            </td>
            <td><div class="text-center"><?php echo $modulo->mostrar_status(); ?></div></td>
            <td>
                <div class="btn-group pull-right">
                    <a class="btn btn-white " data-container="body" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),"action" => "view","id" => $modulo->id_modulo)); ?>"  data-toggle="tooltip" title="Visualizar">
                            <i class="icon-zoom-in"></i>
                    </a>
                    <a class="btn btn-white" data-container="body" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),"action" => "editar","id" => $modulo->id_modulo)); ?>"  data-toggle="tooltip" title="Alterar">
                            <i class="icon-cog"></i>
                    </a>
                    <a class="btn btn-white" data-container="body" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),"action" => "acaos","id_modulo" => $modulo->id_modulo)); ?>"  data-toggle="tooltip" title="Ações" >
                            <i class="icon-magic"></i>
                    </a>
                    <a class="btn btn-white" data-container="body" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),"action" => "pacote","id_modulo" => $modulo->id_modulo)); ?>"  data-toggle="tooltip" title="Pacotes" >
                            <i class="icon-sitemap"></i>
                    </a>
    <?php if ($modulo->ordem > 1) { ?>
                    <a class="btn btn-white" data-container="body" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),"action" => "subir","id_modulo" => $modulo->id_modulo)); ?>"  data-toggle="tooltip" title="Subir">
                            <i class="icon-arrow-up"></i>
                    </a>
    <?php } ?>
    <?php if ($modulo->ordem < TbModulo::pegaUltimaOrdem()) { ?>
                    <a class="btn btn-white" data-container="body" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),"action" => "descer","id_modulo" => $modulo->id_modulo)); ?>"  data-toggle="tooltip" title="Descer">
                            <i class="icon-arrow-down"></i>
                    </a>
    <?php } ?>
                    <a class="btn btn-danger" data-container="body" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),"action" => "excluir","id" => $modulo->id_modulo)); ?>" class="link_excluir" id="ExcluirModulo" data-toggle="tooltip" title="Excluir">
                            <i class="icon-trash"></i>
                    </a>
                </div>
            </td>
			</tr>
<?php } ?>
		</tbody>
<?php } ?>
	</table>
    <div class="panel-footer">
        <?php echo $this->paginationControl($this->modulos, "sliding", "minha_paginacao_control.phtml"); ?>
    </div>
</section>