<section class="panel">
    <header class="panel-heading">ADICIONAR AUTO DE INFRAÇÃO</header>
    <div class="panel-body">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => $this->getRequest()->getActionName())); ?>" method="post" id="formulario" class="formulario">
            <input type="hidden" name="id_agente" id="id_agente" value="<?php echo $this->registro->getId(); ?>" />
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="agente">Agente:</label>
                        <input type="text" name="filtro_caracter" class="form-control" value="<?php echo $this->registro->toString(); ?>" disabled />
                    </div>
                </div>
            <div class="col-md-4">
                    <?php
                    $ctrl = new Escola_Form_Element_Select_Table("id_servico_tipo");
                    $ctrl->setPkName("id_servico_tipo");
                    $ctrl->setModel("TbServicoTipo");
                    $ctrl->setLabel("Tipo:");
                    $ctrl->setAttrib('class', 'form-control');
                    echo $ctrl->render($this);
                    ?>
            </div>
            <div class="col-md-4">
                    <div class="form-group">
                        <div class="col-md-6">
                            <label for="codigo_inicio">Início da Numeração:</label>
                            <input type="text" name="filtro_caracter" id="filtro_caracter" class="form-control caracter" value="A" />
                        </div>
                        <div class="col-md-6">
                            <label for="filtro_codigo_inicio">&nbsp;</label>
                            <input type="text" name="filtro_codigo_inicio" id="filtro_codigo_inicio" value="" class="form-control"/>
                        </div>
                    </div>
            </div>
            <div class="col-md-4">
                    <div class="form-group">
                        <div class="col-md-6">
                        <label for="codigo_final">Final da Numeração:</label>
                            <input type="text" name="caracter_final" id="caracter_final" disabled class="caracter form-control" />
                        </div>
                        <div class="col-md-6">
                            <label for="filtro_codigo_final">&ensp;</label>
                            <input type="text" name="filtro_codigo_final" id="filtro_codigo_final" size="5" value="" class="form-control" />
                        </div>
                    </div>
            </div>
        </form>
    </div>
</section>