<section class="panel" id="idPesquisa" style="display: none">
    <header class="panel-heading">Opções de Pesquisa</header>
    <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "autoinfracao")); ?>" method="post" id="formulario" class="formulario">
    <div class="panel-body">
        <div class="col-md-4">
            <?php
            $ctrl = new Escola_Form_Element_Select_Table("filtro_id_servico_tipo");
            $ctrl->setAttrib("class", "filtro");
            $ctrl->setPkName("id_servico_tipo");
            $ctrl->setModel("TbServicoTipo");
            $ctrl->setValue($this->dados["filtro_id_servico_tipo"]);
            $ctrl->setLabel("Tipo:");
            $ctrl->setAttrib('class', 'form-control');
            echo $ctrl->render($this);
            ?>
        </div>
        <div class="col-md-4">
            <div class="form-group pull-in clearfix">
                <div class="col-sm-6">
                    <label for="filtro_caracter">Início da Numeração:</label>
                    <input type="text" name="filtro_caracter" id="filtro_caracter" class="form-control caracter filtro" value="<?php echo $this->dados["filtro_caracter"]; ?>" />
                </div>
                <div class="col-sm-6">
                    <label>&nbsp;</label>
                    <input type="text" name="filtro_codigo_inicio" id="filtro_codigo_inicio" value="<?php echo $this->dados["filtro_codigo_inicio"]; ?>" class="form-control filtro" />
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group pull-in clearfix">
                <div class="col-sm-6">
                    <label for="filtro_codigo_final">Final da Numeração:</label>
                    <input type="text" name="caracter_final" id="caracter_final" disabled class="form-control caracter filtro" />
                </div>
                <div class="col-sm-6">
                    <label>&nbsp;</label>
                    <input type="text" name="filtro_codigo_final" id="filtro_codigo_final" value="<?php echo $this->dados["filtro_codigo_final"]; ?>" class="form-control filtro" />
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <?php
            $ctrl = new Escola_Form_Element_Select_Table("filtro_id_auto_infracao_status");
            $ctrl->setAttrib("class", "filtro span5");
            $ctrl->setPkName("id_auto_infracao_status");
            $ctrl->setModel("TbAutoInfracaoStatus");
            $ctrl->setValue($this->dados["filtro_id_auto_infracao_status"]);
            $ctrl->setLabel("Status de Auto de Infração:");
            $ctrl->setAttrib('class', 'form-control');
            echo $ctrl->render($this);
            ?>
        </div>
    </div>
    <div class="panel-footer">
        <input type="submit" value="Pesquisar" class="acao btn btn-primary" />
        <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />
    </div>
    </form>
</section>
<section class="panel">
    <header class="panel-heading">Agente: <?php echo $this->registro->toString(); ?></header>
    <table class="table table-striped table-condensed table-hover table-vcenter">
        <thead>
        <tr>
            <th>Tipo</th>
            <th>Código</th>
            <th>Status da Devolução</th>
            <th>Status</th>
            <th width="20%" class="text-right">Operações</th>
        </tr>
        </thead>
        <?php if ($this->registros && count($this->registros)) { ?>
            <tbody>
            <?php
            foreach ($this->registros as $registro) {
                $aids = $registro->findParentRow("TbAutoInfracaoDevolucaoStatus");
                $ais = $registro->findParentRow("TbAutoInfracaoStatus");
                ?>
                <tr>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewautoinfracao", "id" => $registro->getId())); ?>">
                            <?php echo $registro->findParentRow("TbServicoTipo")->toString(); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewautoinfracao", "id" => $registro->getId())); ?>">
                            <?php echo $registro->mostrar_codigo(); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewautoinfracao", "id" => $registro->getId())); ?>">
                            <?php echo ($aids)?$aids->toString():"--"; ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewautoinfracao", "id" => $registro->getId())); ?>">
                            <?php echo $ais->toString(); ?>
                        </a>
                    </td>
                    <td>
                        <div class="btn-group pull-right">
                            <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "viewautoinfracao",
                                "id" => $registro->getId())); ?>" class="btn btn-white" data-toggle="tooltip" data-container="body" title="Visualizar">
                                <i class="icon-search"></i>
                            </a>
                            <?php if ($registro->entregue()) { ?>
                                <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                    "action" => "devolver",
                                    "id" => $registro->getId())); ?>" class="btn btn-white" data-toggle="tooltip" data-container="body" title="Devolver">
                                    <i class="icon-download-alt"></i>
                                </a>
                            <?php } ?>
                            <?php if ($registro->entregue()) { ?>
                                <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                    "action" => "excluirautoinfracao",
                                    "id" => $registro->getId())); ?>" class="btn btn-danger link_excluir" data-toggle="tooltip" data-container="body" title="Excluir">
                                    <i class="icon-trash"></i>
                                </a>
                            <?php } ?>
                        </div>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        <?php } ?>
    </table>
    <div class="panel-footer">
        <?php if ($this->registros && count($this->registros)) {
            echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml");
        }
        ?>
    </div>
</section>