<section class="panel">
    <header class="panel-heading">Lista de Grupos</header>
    <table class="table table-striped table-hover table-vcenter">
        <thead>
        <tr>
            <th>Descrição</th>
            <th>Grupo Inferior</th>
            <th>Padrão</th>
            <th width="25%" class="text-right">Operações</th>
        </tr>
        </thead>
        <?php if ($this->grupos) { ?>
            <tbody>
            <?php
            foreach ($this->grupos as $registro) {
                $inferior = "";
                $m_inferior = $registro->findParentRow("TbGrupo");
                if (count($m_inferior)) {
                    $inferior = $m_inferior->descricao;
                }
                ?>
                <tr>
                    <td>
                        <?php echo $registro->descricao; ?>
                    </td>
                    <td>
                        <?php echo $inferior; ?>
                    </td>
                    <td>
                        <?php echo $registro->mostrarPadrao(); ?>
                    </td>
                    <td width="20%">
                        <div class="btn-group pull-right">
                            <a class="btn btn-white" data-container="body" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "view",
                                "id" => $registro->getId())); ?>" data-toggle="tooltip" title="Visualizar">
                                <i class="icon-zoom-in"></i>
                            </a>
                            <a class="btn btn-white" data-container="body" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "editar",
                                "id" => $registro->getId())); ?>" data-toggle="tooltip" title="Alterar">
                                <i class="icon-cog"></i>
                            </a>
                            <a class="btn btn-white" data-container="body" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "permissoes",
                                "id" => $registro->getId())); ?>" data-toggle="tooltip" title="Permissões">
                                <i class="icon-key"></i>
                            </a>
                            <a class="btn btn-white" data-container="body" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "usuarios",
                                "id" => $registro->getId())); ?>" data-toggle="tooltip" title="Usuários">
                                <i class="icon-group"></i>
                            </a>
                            <a class="btn btn-danger" data-container="body" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "excluir",
                                "id" => $registro->getId())); ?>" class="link_excluir" id="ExcluirGrupo" data-toggle="tooltip" title="Excluir">
                                <i class="icon-trash"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        <?php } ?>
    </table>
    <div class="panel-footer">
        <?php echo $this->paginationControl($this->grupos, "sliding", "minha_paginacao_control.phtml"); ?>
    </div>
</section>
