
<!-- janela adicionar usuário -->
<div id="janela_usuario" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <input type="hidden" name="jan_pagina" id="jan_pagina" />
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel">Adicionar Usuários</h4>
            </div>
            <div class="modal-body">
                <div class="row-fluid">
                    <form action="" method="post" id="form_usuario">
                        <label for="filtro_nome" >Nome: </label>
                        <div class="input-group">
                            <input type="text" name="filtro_nome" id="filtro_nome" class="form-control">
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-primary"><i class="icon-search"></i></button>
                                <button type="reset" id="bt_limpar" class="btn btn-danger"><i class="icon-trash"></i></button>
                            </span>
                        </div>
                    </form>
                    <table class="table table-striped table-hover table-vcenter" id="table_usuario">
                        <thead>
                        <tr>
                            <th>Usuário</th>
                            <th>Situação</th>
                            <th width="20px"></th>
                        </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>

            </div>

            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
            </div>
        </div>
    </div>
</div>

<section class="panel">
    <header class="panel-heading">Usuários do Grupo: <?php echo $this->grupo->toString(); ?></header>
    <form action="<?php echo $this->url(array("controller" => "grupo", "action" => "usuarios")); ?>" method="post" id="formulario" class="formulario">
        <input type="hidden" name="id" id="id" value="<?php echo $this->grupo->getId(); ?>" />
        <table class="table table-striped table-hover table-vcenter">
            <thead>
            <tr>
                <th>C.P.F.</th>
                <th>Nome do Usuário</th>
                <th width="25%" class="text-right">Operações</th>
            </tr>
            </thead>
            <?php if ($this->usuarios) { ?>
                <tbody>
                <?php
                foreach ($this->usuarios as $dado) {
                    $usuario = TbUsuario::pegaPorId($dado["id_usuario"]);
                    $pf = $usuario->pega_pessoa_fisica();
                    ?>
                    <tr>
                        <td><?php echo Escola_Util::formatCpf($pf->cpf); ?></td>
                        <td><?php echo $pf->nome; ?></td>
                        <td>
                            <div class="text-center">
                                <div class="btn-group pull-right">
                                    <a class="btn btn-danger"  data-container="body" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "usuarioexcluir", "id" => $this->grupo->getId(), "id_usuario" => $usuario->getId())); ?>" class="link_excluir" data-toggle="tooltip" title="Excluir"><i class="icon-trash"></i></a>
                                </div>
                            </div>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            <?php } ?>
        </table>
    </form>
    <div class="panel-footer">
        <?php echo $this->paginationControl($this->usuarios, "sliding", "minha_paginacao_control.phtml"); ?>
    </div>
</section>