<section class="panel">
    <header class="panel-heading">
        Cadastro de Relatório
    </header>
    <div class="panel-body">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "editar")); ?>" method="post" id="formulario" class="formulario">
            <input type="hidden" name="id" id="id" value="<?php echo $this->registro->getId(); ?>" />
            <?php if ($this->registro->getId()) { ?>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="codigo">Código:</label>
                        <input type="text" name="codigo" id="codigo" maxlength="10" value="<?php echo $this->registro->getId(); ?>" class="form-control" disabled/>
                    </div>
                </div>
            <?php } ?>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table("id_relatorio_tipo");
                $ctrl->setModel("TbRelatorioTipo");
                $ctrl->setPkName("id_relatorio_tipo");
                $ctrl->setValue($this->registro->id_relatorio_tipo);
                $ctrl->setLabel("Tipo");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="chave">Chave:</label>
                    <input type="text" name="chave" id="chave" maxlength="20" value="<?php echo $this->registro->chave; ?>" class="form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="descricao">Descrição:</label>
                    <textarea name="descricao" id="descricao" class="form-control" rows="6"><?php echo $this->registro->descricao; ?></textarea>
                </div>
            </div>
        </form>
    </div>
</section>