<section class="panel">
    <header class="panel-heading">
        CADASTRO DE VEÍCULOS
    </header>
    <div class="panel-body">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "editar")); ?>" method="post" id="formulario" class="formulario">
            <input type="hidden" name="id" id="id" value="<?php echo $this->registro->getId(); ?>" />
            <?php if ($this->registro->getId()) { ?>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="codigo">Código:</label>
                        <input type="text" name="codigo" id="codigo" maxlength="10" value="<?php echo $this->registro->getId(); ?>" class="form-control" disabled/>
                    </div>
                </div>
            <?php } ?>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="chassi">Chassi:</label>
                    <input type="text" name="chassi" id="chassi" maxlength="30" value="<?php echo $this->registro->chassi; ?>" class="form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="placa">Placa:</label>
                    <input type="text" name="placa" id="placa" maxlength="10" value="<?php echo $this->registro->placa; ?>" class="form-control placa" />
                </div>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table_Crud_VeiculoTipo("id_veiculo_tipo");
                $ctrl->setPkName("id_veiculo_tipo");
                $ctrl->setModel("TbVeiculoTipo");
                $ctrl->setValue($this->registro->id_veiculo_tipo);
                $ctrl->setLabel("Tipo: ");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table_Crud_VeiculoEspecie("id_veiculo_especie");
                $ctrl->setPkName("id_veiculo_especie");
                $ctrl->setModel("TbVeiculoEspecie");
                $ctrl->setValue($this->registro->id_veiculo_especie);
                $ctrl->setLabel("Espécie: ");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table_Crud_VeiculoCategoria("id_veiculo_categoria");
                $ctrl->setPkName("id_veiculo_categoria");
                $ctrl->setModel("TbVeiculoCategoria");
                $ctrl->setValue($this->registro->id_veiculo_categoria);
                $ctrl->setLabel("Categoria: ");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table_Pessoa("proprietario_id_pessoa");
                $ctrl->setValue($this->registro->proprietario_id_pessoa);
                $ctrl->setLabel("Proprietário: ");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table("id_uf");
                $ctrl->setPkName("id_uf");
                $ctrl->setModel("TbUf");
                $ctrl->setValue($this->registro->id_uf);
                $ctrl->setLabel("Estado: ");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table_Crud_Municipio("id_municipio");
                $ctrl->setPkName("id_municipio");
                $ctrl->setModel("TbMunicipio");
                $ctrl->setValue($this->registro->id_municipio);
                $ctrl->setLabel("Município: ");
                $ctrl->set_id_uf("id_uf");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table_Crud_Combustivel("id_combustivel");
                $ctrl->setPkName("id_combustivel");
                $ctrl->setModel("TbCombustivel");
                $ctrl->setValue($this->registro->id_combustivel);
                $ctrl->setLabel("Combustível: ");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table_Crud_Cor("id_cor");
                $ctrl->setPkName("id_cor");
                $ctrl->setModel("TbCor");
                $ctrl->setValue($this->registro->id_cor);
                $ctrl->setLabel("Cor: ");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table_Crud_Fabricante("id_fabricante");
                $ctrl->setPkName("id_fabricante");
                $ctrl->setModel("TbFabricante");
                $ctrl->setValue($this->registro->id_fabricante);
                $ctrl->setLabel("Fabricante: ");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="modelo">Modelo:</label>
                    <input type="text" name="modelo" id="modelo" maxlength="100" value="<?php echo $this->registro->modelo; ?>" class="form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="ano_fabricacao">Ano Fabricação:</label>
                    <input type="text" name="ano_fabricacao" id="ano_fabricacao" maxlength="10" value="<?php echo $this->registro->ano_fabricacao; ?>" class="form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="ano_modelo">Ano Modelo:</label>
                    <input type="text" name="ano_modelo" id="ano_modelo" maxlength="10" value="<?php echo $this->registro->ano_modelo; ?>" class="form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="data_aquisicao">Data Aquisição:</label>
                    <input type="text" name="data_aquisicao" id="data_aquisicao" maxlength="10" value="<?php echo $this->registro->data_aquisicao; ?>" class="form-control data" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="renavan">Renavan:</label>
                    <input type="text" name="renavan" id="renavan" maxlength="30" value="<?php echo $this->registro->renavan; ?>" class="form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="dut">DUT:</label>
                    <input type="text" name="dut" id="dut" maxlength="30" value="<?php echo $this->registro->dut; ?>" class="form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="tara">Tara (Kg):</label>
                    <input type="text" name="tara" id="tara" maxlength="30" value="<?php echo $this->registro->tara; ?>" class="form-control moeda" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="lotacao">Lotação:</label>
                    <input type="text" name="lotacao" id="lotacao" maxlength="30" value="<?php echo $this->registro->lotacao; ?>" class="form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="isento">Isento:</label>
                    <select name="isento" id="isento" class="form-control">
                        <option value="" <?php echo (!$this->registro->isento)?"selected":""; ?>>==> SELECIONE <==</option>
                        <option value="S" <?php echo ($this->registro->isento == "S")?"selected":""; ?>>SIM</option>
                        <option value="N" <?php echo ($this->registro->isento == "N")?"selected":""; ?>>NÃO</option>
                    </select>
                </div>
            </div>
        </form>
    </div>
</section>