<?php 
$txt_notificacao = $txt_data_hora = $txt_documento = $txt_resumo = $txt_valor_total = "--";
$txt_data_hora = Escola_Util::formatData($this->registro->data_jari) . " - " . $this->registro->hora_jari;
$not = $this->registro->findParentRow("TbAutoInfracaoNotificacao");
if ($not) {
    $txt_notificacao = $not->toString();
    $valor_total = $not->pegaValorTotal();
    $txt_valor_total = Escola_Util::number_format($valor_total);
}
$doc = $this->registro->findParentRow("TbDocumento");
if ($doc) {
    $txt_documento = $doc->toString();
    $txt_resumo = $doc->resumo;
}
?>
<section class="panel">
    <header class="panel-heading">
        RESPONDER REQUERIMENTO JARI
    </header>
    <div class="panel-body">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => $this->getRequest()->getActionName())); ?>" method="post" id="formulario" class="formulario form-horizontal">
            <input type="hidden" name="id" id="id" value="<?php echo $this->registro->getId(); ?>" />
            <dl class="dl-horizontal">
                <dt>Código:</dt>
                <dd><?php echo $this->registro->getId(); ?></dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>Notificação de Auto de Infração:</dt>
                <dd><?php echo $txt_notificacao; ?></dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>Data / Hora Infração:</dt>
                <dd><?php echo $txt_data_hora; ?></dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>Documento:</dt>
                <dd><?php echo $txt_documento; ?></dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>Resumo Doc:</dt>
                <dd><?php echo $txt_resumo; ?></dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>Valor (R$):</dt>
                <dd><?php echo $txt_valor_total; ?></dd>
            </dl>
            <div class="col md-4">
            <div class="form-group">
                <label for="id_requerimento_jari_status">Escolha uma Opção:</label>
                <select name="id_requerimento_jari_status" id="id_requerimento_jari_status" class="form-control">
                    <option value="">==> SELECIONE <==</option>
                    <?php foreach ($this->rjss as $rjs) {
                        if (!$rjs->aguardando_resposta()) {
                            ?>
                            <option value="<?php echo $rjs->getId(); ?>"><?php echo $rjs->toString(); ?></option>
                        <?php }} ?>
                </select>
            </div>
            </div>
            <div class="col md-4 linha_infracao" style="display:none">
            <div class="form-group " >
                <label for="">Infrações:</label>

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th colspan="4">Selecione as Infrações que deverão ser retiradas da Notificação.</th>
                    </tr>
                    <tr>
                        <th></th>
                        <th>Código</th>
                        <th>Infração</th>
                        <th>Valor</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->infracoes as $infracao) {
                        $txt_codigo = $txt_infracao = $txt_valor = "--";
                        $txt_codigo = $infracao->codigo;
                        $txt_infracao = $infracao->descricao;
                        $valor = $infracao->pega_valor();
                        if ($valor) {
                            $txt_valor = $valor->toString();
                        }
                        ?>
                        <tr>
                            <td width="20px"><div class="text-center"><input type="checkbox" name="id_infracao[]" class="id_infracao" id="id_infracao" value="<?php echo $infracao->getId(); ?>" /></div></td>
                            <td><div class="text-center"><a href="#" class="link_infracao"><?php echo $txt_codigo; ?></a></div></td>
                            <td><a href="#" class="link_infracao"><?php echo $txt_infracao; ?></a></td>
                            <td><div class="text-center"><a href="#" class="link_infracao"><?php echo $txt_valor; ?></a></div></td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>

            </div>
            </div>
            <div class="col md-4 linha_observacao" style="display:none">
                <div class="form-group " >
                    <label for="observacao">Justifique sua decisão:</label>
                    <textarea name="observacao" id="observacao" rows="6" class="form-control"></textarea>
                </div>
            </div>
        </form>
    </div>
</section>