<section class="panel">
    <header class="panel-heading">
        Importar Arquivo de Retorno
    </header>
    <div class="panel-body">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => $this->getRequest()->getActionName())); ?>" method="post" id="formulario" class="formulario" enctype="multipart/form-data">
            <div class="col-md-4">
                <div class="form-group">
                    <label for="arquivo" class="control-label">Tipo de Retorno:</label>
                    <select name="id_retorno_tipo" id="id_retorno_tipo" class="form-control">
                        <option value="">==> SELECIONE <==</option>
                        <?php foreach ($this->rts as $rt) { ?>
                            <option value="<?php echo $rt->getId(); ?>"><?php echo $rt->toString(); ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="arquivo" class="control-label">Arquivo de Retorno:</label>
                    <input type="file" name="arquivo" id="arquivo" class="form-control" />
                </div>
            </div>
        </form>
    </div>
</section>