<?php
$tb = new TbSistema();
$sistema = $tb->pegaSistema();
$pj = $sistema->findParentRow("TbPessoaJuridica");
$pessoa = $pj->findParentRow("TbPessoa");
$arquivo = $pessoa->getFoto();
if ($arquivo) {
    //$filename = $arquivo->pegaLinkFisico();
    ?>
    <center><img src="<?php echo $this->url(array("controller" => "arquivo", "action" => "view", "id" => $arquivo->getId())); ?>" width="15%" /></center>
<?php } ?>
<section class="vbox flex">
<div class="row m-n">
    <div class="col-md-4 col-md-offset-4 m-t-lg">
        <section class="panel">
            <header class="panel-heading text-center">
                Acesso
            </header>
            <form action="<?php echo $this->url(array("controller" => "auth", "action" => "identify")); ?>" method="post" id="formulario"  class="panel-body">
                <div class="form-group">
                    <label class="control-label" for="login_cpf">CPF</label>
                    <input type="text" name="login_cpf" id="login_cpf" placeholder="___.___.___-__" class="form-control cpf" value="<?php echo $this->login_cpf; ?>">
                </div>
                <div class="form-group">
                    <label class="control-label">SENHA</label>
                    <input type="password" name="login_senha" id="login_senha" placeholder="SENHA" class="form-control">
                </div>
                <a href="<?php echo $this->url(array("controller" => "auth", "action" => "recuperasenha")); ?>" class="pull-right btn btn-warning"><small>Recuperar Senha</small></a>
                <button type="submit" class="btn btn-info">Login</button>
            </form>
        </section>
    </div>
</div>
</section>