<div class="row">
    <?php foreach ($this->pacotes as $pacote) { ?>
    <div class="col-md-3">
        <a href="<?php echo $this->url(array("controller" => "auth", "action" => "pacote", "id_pacote" => $pacote->getId())); ?>">
        <section class="panel no-borders hbox">
            <aside class="bg-info r-l text-center v-middle">
            <div class="wrapper">
                <i class="<?php echo $pacote->icone; ?> icon-4x"></i>                      
            </div>
            </aside>
            <aside>
            <div class="wrapper text-center">
                <p class="h4"><?php echo $pacote->descricao; ?></p>
                <span><?php echo $pacote->resumo; ?></span>
            </div>
            </aside>
        </section>
        </a>
    </div>
    <?php } ?>
</div>