<section class="panel">
    <header class="panel-heading">
        CONFIRMAR PAGAMENTO DE NOTIFICAÇÃO DE AUTO DE INFRAÇÃO
    </header>
    <div class="panel-body">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => $this->getRequest()->getActionName())); ?>" method="post" id="formulario" class="formulario">
            <?php echo $this->registro->form_pagamento($this); ?>
        </form>
    </div>
</section>