<section class="panel">
    <header class="panel-heading">Folha de Ponto</header>
    <div class="panel-body">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "imprimir")); ?>" method="post" id="formulario" class="formulario" enctype="multipart/form-data">
            <div class="form-group">
                <label for="ano_mes" >Mês:</label>
                <div class="controls">
                    <select name="ano_mes" id="ano_mes" class="form-control">
                        <?php
                        $data = new Zend_Date();
                        for ($i = 6; $i >= 1; $i--) {
                            $k = $data->get("M");
                            $mes = Escola_Util::pegaMes($k);
                            $selected = "";
                            ?>
                            <option value="<?php echo $data->get("YYYY"); ?>_<?php echo $k; ?>" <?php echo $selected; ?>><?php echo $mes; ?> / <?php echo $data->get("YYYY"); ?></option>
                            <?php $data->sub('1', Zend_Date::MONTH); } ?>
                    </select>
                </div>
            </div>
            <?php echo $this->grade; ?>
        </form>
    </div>
</section>