<section class="panel">
    <header class="panel-heading">CADASTRO DE PESSOA</header>
    <div class="panel-body">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "editar")); ?>" method="post" id="formulario" class="formulario">
            <input type="hidden" name="id" id="id" value="<?php echo $this->registro->getId(); ?>" />
            <input type="hidden" name="flag" id="flag" value="salvar" />
            <input type="hidden" name="id_pessoa_tipo" id="id_pessoa_tipo" value="<?php echo $this->registro->id_pessoa_tipo; ?>" />
            <input type="hidden" name="jan_id_pessoa_tipo" id="jan_id_pessoa_tipo" value="<?php echo $this->registro->id_pessoa_tipo; ?>" />
            <?php if ($this->pessoa_tipo->pf()) { ?>
                <input type="hidden" name="cpf" id="cpf" value="<?php echo $this->filho->cpf; ?>" />
            <?php } elseif ($this->pessoa_tipo->pj()) { ?>
                <input type="hidden" name="cnpj" id="cnpj" value="<?php echo $this->filho->cnpj; ?>" />
            <?php } ?>
            <?php if ($this->registro->getId()) { ?>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="codigo">Código:</label>
                        <input type="text" name="codigo" id="codigo" maxlength="10" value="<?php echo $this->registro->getId(); ?>" class="form-control" disabled/>
                    </div>
                </div>
            <?php } ?>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="Tipo">Tipo:</label>
                    <input type="text" name="Tipo" id="Tipo" maxlength="10" value="<?php echo $this->registro->findParentRow("TbPessoaTipo")->toString(); ?>" class="form-control" disabled/>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="email">E-Mail:</label>
                    <input type="text" name="email" id="email" value="<?php echo $this->registro->email; ?>" class="form-control" size="60" />
                </div>
            </div>
            <?php echo $this->filho->render($this); ?>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="possui_cnh">Possui CNH:</label>
                    <select name="possui_cnh" id="possui_cnh" class="form-control">
                        <option value="N" <?php echo (!$this->possui_cnh)?"selected":""; ?> >NÃO</option>
                    </select>
                </div>
            </div>

                <?php echo ($this->registro->pf())?$this->pessoa_motorista->render($this):""; ?>

            <div class="col-md-4">
                <div class="form-group">
                    <label for="telefone_fixo">Fixo:</label>
                    <input type="text" name="telefone_fixo" id="telefone_fixo" value="<?php echo $this->fixo->toString(); ?>" class="form-control telefone" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="telefone_celular">Celular:</label>
                    <input type="text" name="telefone_celular" id="telefone_celular" value="<?php echo $this->celular->toString(); ?>" class="form-control telefone" />
                </div>
            </div>
            <?php echo $this->endereco->render($this); ?>
        </form>
    </div>
</section>