<section class="panel" id="idPesquisa">
    <header class="panel-heading">Opções de Pesquisa</header>
    <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => $this->getRequest()->getActionName())); ?>" method="post" id="formulario" class="formulario">
    <div class="panel-body">
        <div class="row">
            <?php if ($pts) { ?>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="filtro_id_pessoa_tipo">Tipo de Pessoa:</label>
                        <select name="filtro_id_pessoa_tipo" id="filtro_id_pessoa_tipo" class="filtro form-control">
                            <option value="" <?php echo (!$this->dados["filtro_id_pessoa_tipo"])?"selected":""; ?>>==> SELECIONE <==</option>
                            <?php foreach ($pts as $pt) { ?>
                                <option value="<?php echo $pt->getId(); ?>" rel="<?php echo Escola_Util::minuscula($pt->chave); ?>" <?php echo ($pt->getId() == $this->dados["filtro_id_pessoa_tipo"])?"selected":""; ?>><?php echo $pt->toString(); ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
            <?php } ?>
            <div class="col-md-4 filtro_pf">
                <div class="form-group">
                    <label for="filtro_cpf">C.P.F.:</label>
                    <input type="text" name="filtro_cpf" id="filtro_cpf" value="<?php echo $this->dados["filtro_cpf"]; ?>" class="form-control filtro cpf" />
                </div>
            </div>
            <div class="col-md-4 filtro_pj">
                <div class="form-group">
                    <label for="filtro_cnpj">C.N.P.J.:</label>
                    <input type="text" name="filtro_cnpj" id="filtro_cnpj" value="<?php echo $this->dados["filtro_cnpj"]; ?>" class="form-control filtro cnpj" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="filtro_nome">Nome da Pessoa:</label>
                    <input type="text" name="filtro_nome" id="filtro_nome" value="<?php echo $this->dados["filtro_nome"]; ?>" class="form-control filtro" />
                </div>
            </div>
        </div>
    </div>
    <div class="panel-footer">
        <input type="submit" value="Pesquisar" class="acao btn btn-primary" />
        <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn btn-white" />
    </div>
    </form>
</section>
<div id="janela_pessoa_tipo" class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Adicionar Pessoa</h4>
            </div>
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "editar")); ?>" method="post" id="jan_formulario" class="formulario">
                <div class="modal-body">
                    <div class="row">
                        <?php
                        $tb = new TbPessoaTipo();
                        $pts = $tb->listar();
                        if ($pts) {
                            ?>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="jan_id_pessoa_tipo">Tipo de Pessoa:</label>
                                    <select name="jan_id_pessoa_tipo" id="jan_id_pessoa_tipo" class="filtro form-control">
                                        <option value="" <?php echo (!$this->dados["filtro_id_pessoa_tipo"])?"selected":""; ?>>==> SELECIONE <==</option>
                                        <?php foreach ($pts as $pt) { ?>
                                            <option value="<?php echo $pt->getId(); ?>" rel="<?php echo Escola_Util::minuscula($pt->chave); ?>" <?php echo ($pt->getId() == $this->dados["filtro_id_pessoa_tipo"])?"selected":""; ?>><?php echo $pt->toString(); ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                        <?php } ?>
                        <div class="col-md-4 jan_pf">
                            <div class="form-group">
                                <label for="jan_cpf">C.P.F.:</label>
                                <input type="text" name="jan_cpf" id="jan_cpf" class="form-control cpf" />
                            </div>
                        </div>
                        <div class="col-md-4 jan_pj">
                            <div class="form-group">
                                <label for="jan_cnpj">C.N.P.J.:</label>
                                <input type="text" name="jan_cnpj" id="jan_cnpj" class="form-control cnpj" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-white" data-dismiss="modal" aria-hidden="true">Fechar</button>
                    <input type="submit" value="Salvar" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>
<section class="panel">
    <header class="panel-heading">Lista de Pessoas</header>
    <table class="table table-striped table-condensed table-hover">
        <thead>
        <tr>
            <th>Tipo</th>
            <th>C.P.F./C.N.P.J.</th>
            <th>Nome</th>
            <th>E-Mail</th>
            <th width="25%" class="text-right">Operações</th>
        </tr>
        </thead>
        <?php if ($this->registros && count($this->registros)) { ?>
            <tbody>
            <?php
            foreach ($this->registros as $registro) {
                $pt = $registro->findParentRow("TbPessoaTipo");
                ?>
                <tr>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo $pt->toString(); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo $registro->mostrar_documento(); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo $registro->mostrar_nome(); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo $registro->email; ?>
                        </a>
                    </td>
                    <td>
                        <div class="btn-group pull-right">
                            <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "telefone",
                                "id_pessoa" => $registro->getId(), "id" => 0)); ?>" class="btn btn-white" data-toggle="tooltip" data-container="body" title="Telefones">
                                <i class="icon-phone"></i>
                            </a>
                            <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "ib",
                                "id_pessoa" => $registro->getId(), "id" => 0)); ?>" class="btn btn-white" data-toggle="tooltip" data-container="body" title="Informações Bancárias">
                                <i class="icon-money"></i>
                            </a>
                            <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "view",
                                "id" => $registro->getId())); ?>" class="btn btn-white" data-toggle="tooltip" data-container="body" title="Visualizar">
                                <i class="icon-search"></i>
                            </a>
                            <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "editar",
                                "id" => $registro->getId())); ?>" class="btn btn-white" data-toggle="tooltip" data-container="body" title="Editar">
                                <i class="icon-cog"></i>
                            </a>
                            <?php if ($pt->pf()) { ?>
                                <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                    "action" => "foto",
                                    "id" => $registro->getId())); ?>" class="btn btn-white" data-toggle="tooltip" data-container="body" title="Foto">
                                    <i class="icon-camera-retro"></i>
                                </a>
                            <?php } ?>
                            <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "excluir",
                                "id" => $registro->getId())); ?>" class="btn btn-danger link_excluir" data-toggle="tooltip" data-container="body" title="Excluir">
                                <i class="icon-trash"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        <?php } ?>
    </table>
    <div class="panel-footer">

        <?php if ($this->registros && count($this->registros)) {
            echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml");
        }
        ?>
    </div>
</section>
