<section class="panel">
    <header class="panel-heading">Pessoa: <?php echo $this->pessoa->toString(); ?></header>
    <table class="table table-striped table-condensed table-hover table-vcenter">
        <thead>
        <tr>
            <th>Tipo</th>
            <th>DDD</th>
            <th>Número</th>
            <th width="20%" class="text-right">Operações</th>
        </tr>
        </thead>
        <?php if ($this->registros && count($this->registros)) { ?>
            <tbody>
            <?php
            foreach ($this->registros as $registro) {
                $telefone = $registro->getObjeto();
                ?>
                <tr>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewtelefone", "id" => $registro->getId())); ?>">
                            <?php echo $telefone->findParentRow("TbTelefoneTipo")->toString(); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewtelefone", "id" => $registro->getId())); ?>">
                            <?php echo $telefone->ddd; ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewtelefone", "id" => $registro->getId())); ?>">
                            <?php echo $telefone->numero; ?>
                        </a>
                    </td>
                    <td>
                        <div class="btn-group pull-right">
                            <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "viewtelefone",
                                "id" => $registro->getId())); ?>" class="btn btn-white" title="Visualizar">
                                <i class="icon-search"></i>
                            </a>
                            <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "editartelefone",
                                "id" => $registro->getId())); ?>" class="btn btn-white" title="Editar">
                                <i class="icon-cog"></i>
                            </a>
                            <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "excluirtelefone",
                                "id" => $registro->getId())); ?>" class="btn btn-danger link_excluir" title="Excluir">
                                <i class="icon-trash"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        <?php } ?>
    </table>
    <div class="panel-footer">
        <?php if ($this->registros && count($this->registros)) {
            echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml");
        }
        ?>
    </div>
</section>