<section class="panel">
    <header class="panel-heading">Visualização de Pessoa > Telefone</header>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>ID:</dt>
            <dd><?php echo $this->registro->getId(); ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Pessoa:</dt>
            <dd><?php echo $this->pessoa->toString(); ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Tipo:</dt>
            <dd><?php echo $this->telefone->findParentRow("TbTelefoneTipo")->toString(); ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>DDD:</dt>
            <dd><?php echo $this->telefone->ddd; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Número:</dt>
            <dd><?php echo $this->telefone->numero; ?></dd>
        </dl>
    </div>
</section>