<form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "funcionario")); ?>" method="post" id="formulario" class="formulario">
    <input type="hidden" name="id" id="id" value="<?php echo $this->setor->getId(); ?>" />
<section class="panel" id="idPesquisa">
    <header class="panel-heading">
        Opções de Pesquisa
    </header>

    <div class="panel-body">
        <div class="col-md-4">
            <div class="form-group">
                <label for="filtro_cargo">Cargo:</label>
                <input type="text" class="filtro form-control" name="filtro_cargo" id="filtro_cargo" value="<?php echo $this->getRequest()->getPost("filtro_cargo"); ?>" />
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="filtro_cpf">C.P.F.:</label>
                <input type="text" name="filtro_cpf" id="filtro_cpf" value="<?php echo $this->getRequest()->getPost("filtro_cpf"); ?>" class="filtro cpf form-control" />
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="filtro_nome">Nome:</label>
                <input type="text" class="filtro form-control" name="filtro_nome" id="filtro_nome" value="<?php echo $this->getRequest()->getPost("filtro_nome"); ?>" />
            </div>
        </div>
    </div>
    <div class="panel-footer text-right">
        <input type="submit" value="Pesquisar" class="btn btn-primary" />
        <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />
    </div>




</section>
<div id="janela_cpf" class="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 id="myModalLabel" class="modal-title">Adicionar Funcionário - Informe o C.P.F.</h4>
            </div>
            <div class="modal-body">
                <div class="alert" id="msg_erro_cpf">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <div class="mensagem_erro"></div>
                </div>
                <div class="form-group">
                    <label for="jan_cpf">C.P.F.:</label>
                    <?php
                    $ctrl = new Escola_Form_Element_Cpf("jan_cpf");
                    $ctrl->setValue("");
                    $ctrl->setAttrib('class', 'form-control');
                    echo $ctrl->render($this);
                    ?>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
                <input type="submit" value="Procurar" class="btn btn-primary" id="bt_jan_procurar" />
            </div>
        </div>
    </div>
</div>
</form>
<section class="panel">
    <header class="panel-heading">
        Setor: <?php echo $this->setor->toString(); ?>
    </header>
    <table class="table table-striped table-condensed table-hover">
        <thead>
        <tr>
            <th>C.P.F.</th>
            <th>Nome</th>
            <th>Matrícula</th>
            <th>Cargo</th>
            <th>Função</th>
            <th>Tipo de Lotação</th>
            <th>Chefe</th>
            <th>Situação</th>
            <th class="text-right" style="width: 15%">Operações</th>
        </tr>
        </thead>
        <?php if ($this->registros && count($this->registros)) { ?>
            <tbody>
            <?php
            foreach ($this->registros as $registro) {
                $funcionario_funcao = "";
                $funcionario = $registro->findParentRow("TbFuncionario");
                $pf = $funcionario->findParentRow("TbPessoaFisica");
                $ff = $registro->findParentRow("TbFuncionarioFuncao");
                if ($ff) {
                    $funcionario_funcao = $ff->toString();
                }
                ?>
                <tr>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewlotacao", "id_lotacao" => $registro->getId())); ?>">
                            <?php echo $this->formatCpf($pf->cpf); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewlotacao", "id_lotacao" => $registro->getId())); ?>">
                            <?php echo $pf->nome; ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewlotacao", "id_lotacao" => $registro->getId())); ?>">
                            <?php echo $funcionario->matricula; ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewlotacao", "id_lotacao" => $registro->getId())); ?>">
                            <?php echo $funcionario->findParentRow("TbCargo")->toString(); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewlotacao", "id_lotacao" => $registro->getId())); ?>">
                            <?php echo $funcionario_funcao; ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewlotacao", "id_lotacao" => $registro->getId())); ?>">
                            <?php echo $registro->findParentRow("TbLotacaoTipo")->toString(); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewlotacao", "id_lotacao" => $registro->getId())); ?>">
                            <?php echo $registro->mostrarChefe(); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "viewlotacao", "id_lotacao" => $registro->getId())); ?>">
                            <?php echo $funcionario->findParentRow("TbFuncionarioSituacao")->toString(); ?>
                        </a>
                    </td>
                    <td>
                        <div class="btn-group pull-right">
                            <a data-container="body" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "viewlotacao",
                                "id_lotacao" => $registro->getId())); ?>" class="btn btn-white" data-toggle="tooltip" title="Visualizar">
                                <i class="icon-search"></i>
                            </a>
                            <a data-container="body" href="<?php echo $this->url(array("controller" => "setor", "action" => "addfuncionario")); ?>" id="<?php echo $pf->cpf; ?>" class="btn btn-white link_alterar" data-toggle="tooltip" title="Alterar">
                                <i class="icon-cog"></i>
                            </a>
                            <a data-container="body" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "excluirlotacao",
                                "id_lotacao" => $registro->getId())); ?>" class="btn btn-danger link_excluir" data-toggle="tooltip" title="Excluir">
                                <i class="icon-trash"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        <?php } ?>
    </table>
</section>