<section class="panel" id="idPesquisa">
    <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "index")); ?>" method="post" id="formulario" class="formulario">
    <header class="panel-heading">
        Opções de Pesquisa
    </header>
    <div class="panel-body">
        <div class="col-md-4"><div class="form-group">
                <label for="filtro_sigla" class="control-label">Sigla:</label>
                <input type="text" class="filtro form-control" name="filtro_sigla" id="filtro_sigla" value="<?php echo $this->getRequest()->getPost("filtro_sigla"); ?>" />
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                <label for="filtro_descricao" class="control-label">Descrição:</label>
                <input type="text" class="filtro form-control" name="filtro_descricao" id="filtro_descricao" value="<?php echo $this->getRequest()->getPost("filtro_descricao"); ?>" />
            </div>
        </div>
    </div>
    <div class="panel-footer text-right">
        <input type="submit" value="Pesquisar" class="btn btn-primary" />
        <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />
    </div>
    </form>
</section>
<section class="panel">
    <header class="panel-heading">
        SETORES
    </header>

        <table class="table table-striped table-condensed table-hover">
            <thead>
            <tr>
                <th>Tipo</th>
                <th>Nível</th>
                <th>Sigla</th>
                <th>Descrição</th>
                <th>Setor Superior</th>
                <th>Protocolo</th>
                <th class="text-right" style="width: 20%">Operações</th>
            </tr>
            </thead>
            <?php if (count($this->registros)) { ?>
                <tbody>
                <?php
                foreach ($this->registros as $registro) {
                    $superior = "";
                    $sup = $registro->findParentRow("TbSetor");
                    if ($sup) {
                        $superior = $sup->toString();
                    }
                    ?>
                    <tr>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->findParentRow("TbSetorTipo")->descricao; ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->findParentRow("TbSetorNivel")->descricao; ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->sigla; ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->descricao; ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $superior;  ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->mostrarProtocolo();  ?>
                            </a>
                        </td>
                        <td>
                            <div class="btn-group pull-right">
                                <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                    "action" => "view",
                                    "id" => $registro->getId())); ?>" class="btn btn-white" data-toggle="tooltip" data-container="body" title="Visualizar">
                                    <i class="icon-search"></i>
                                </a>
                                <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                    "action" => "editar",
                                    "id" => $registro->getId())); ?>" class="btn btn-white" data-toggle="tooltip" data-container="body" title="Editar">
                                    <i class="icon-cog"></i>
                                </a>
                                <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                    "action" => "funcionario",
                                    "id" => $registro->getId())); ?>" class="btn btn-white" data-toggle="tooltip" data-container="body" title="Funcionários">
                                    <i class="icon-group"></i>
                                </a>
                                <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                    "action" => "excluir",
                                    "id" => $registro->getId())); ?>" class="btn btn-danger link_excluir" data-toggle="tooltip" data-container="body" title="Excluir">
                                    <i class="icon-trash"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            <?php } ?>
        </table>

</section>
<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">


<?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
        </div>
    </div>
</div>