<section class="panel">
    <header class="panel-heading">Setor: <?php echo $this->setor->toString(); ?></header>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>C.P.F.:</dt>
            <dd><?php echo $this->formatCpf($this->pf->cpf); ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Nome:</dt>
            <dd><?php echo $this->pf->nome; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>E-Mail:</dt>
            <dd><?php echo $this->pf->pega_pessoa()->email; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Data de Nascimento:</dt>
            <dd><?php echo $this->pf->mostrarDataNascimento(); ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Identidade - Número:</dt>
            <dd><?php echo $this->pf->identidade_numero; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Identidade - Órgão Expedidor:</dt>
            <dd><?php echo $this->pf->identidade_orgao_expedidor; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Identidade - UF:</dt>
            <dd><?php echo $this->pf->pegaIdentidadeUf()->toString(); ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Matrícula:</dt>
            <dd><?php echo $this->funcionario->matricula; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Cargo:</dt>
            <dd><?php echo $this->funcionario->findParentRow("TbCargo")->toString(); ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Data de Ingresso:</dt>
            <dd><?php echo $this->funcionario->mostrarDataIngresso(); ?></dd>
        </dl>
        <?php if ($funcao = $this->registro->findParentRow("TbFuncionarioFuncao")) { ?>
            <dl class="dl-horizontal">
                <dt>Cargo Função:</dt>
                <dd><?php echo $funcao->toString(); ?></dd>
            </dl>
        <?php } ?>
        <dl class="dl-horizontal">
            <dt>Chefe:</dt>
            <dd><?php echo $this->registro->mostrarChefe(); ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Tipo de Lotação:</dt>
            <dd><?php echo $this->registro->findParentRow("TbLotacaoTipo")->toString(); ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Status:</dt>
            <dd><?php echo $this->funcionario->findParentRow("TbFuncionarioSituacao")->toString(); ?></dd>
        </dl>
    </div>
</section>