<section class="panel">
    <header class="panel-heading">
        Visualizar Grupo de Transporte
    </header>
    <div class="panel-body">
        <dl class="dl-horizontal">
                    <dt>Código:</dt>
                    <dd><?php echo $this->registro->getId(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Chave:</dt>
                    <dd><?php echo $this->registro->chave; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Descrição:</dt>
                    <dd><?php echo $this->registro->descricao; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Possui Concessão:</dt>
                    <dd><?php echo $this->registro->mostrar_possui_concessao(); ?></dd>
                </dl>
<?php
$txt_convenio = "--";
$bc = $this->registro->findParentRow("TbBancoConvenio");
if ($bc) {
    $txt_convenio = $bc->toString();
}
?>
                <dl class="dl-horizontal">
                    <dt>Convênio:</dt>
                    <dd><?php echo $txt_convenio; ?></dd>
                </dl>
    </div>
</section> 
          