<section class="panel" id="idPesquisa" style="display: none;">
    <header class="panel-heading">Opções de Pesquisa</header>
    <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "index")); ?>" method="post" id="formulario" class="formulario">
    <div class="panel-body">
        <?php
        $tb = new TbDocumentoTipoTarget();
        $dtt = $tb->getPorChave("A");
        $tb = new TbDocumentoTipo();
        $dts = $tb->listar(array("filtro_id_documento_tipo_target" => $dtt->getId()));
        if ($dts && count($dts)) {
            ?>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="filtro_id_documento_tipo">Tipo</label>
                    <select name="filtro_id_documento_tipo" id="filtro_id_documento_tipo" class="filtro form-control">
                        <option value="" <?php echo (!$this->dados["filtro_id_documento_tipo"])?"selected":""; ?>>==> SELECIONE <==</option>
                        <?php foreach ($dts as $dt) { ?>
                            <option value="<?php echo $dt->getId(); ?>"  <?php echo ($this->dados["filtro_id_documento_tipo"] == $dt->getId())?"selected":""; ?>><?php echo $dt->toString(); ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
        <?php } ?>
        <div class="col-md-4">
            <div class="form-group">
                <label for="filtro_numero">Número:</label>
                <input type="text" class="filtro form-control" name="filtro_numero" id="filtro_numero" value="<?php echo $this->dados["filtro_id_documento_tipo"]; ?>" />
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="filtro_ano">Ano:</label>
                <input type="text" class="filtro form-control" name="filtro_ano" id="filtro_ano" value="<?php echo $this->dados["filtro_ano"]; ?>" />
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label for="filtro_ano">Resumo:</label>
                <textarea name="filtro_resumo" id="filtro_resumo" rows="6" class="filtro form-control"><?php echo $this->dados["filtro_resumo"]; ?></textarea>
            </div>
        </div>
    </div>
    <div class="panel-footer">
        <input type="submit" value="Pesquisar" class="btn btn-primary" />
        <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn btn-white" />
    </div>
    </form>
</section>

<section class="panel">
    <header class="panel-heading">Lista de Documentos Administrativos</header>
    <table class="table table-striped table-hover table-vcenter">
        <thead>
        <tr>
            <th>Data / Hora Criação</th>
            <th>Tipo</th>
            <th>Número</th>
            <th>Resumo</th>
            <th>Arquivo</th>
            <th width="20%" class="text-right">Operações</th>
        </tr>
        </thead>
        <?php if ($this->registros && count($this->registros)) { ?>
            <tbody>
            <?php
            foreach ($this->registros as $registro) {
                $registro = TbDocumento::pegaPorId($registro["id_documento"]);
                $arquivo = $registro->pega_arquivo();
                ?>
                <tr>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo Escola_Util::formatData($registro->data_criacao); ?> - <?php echo $registro->hora_criacao; ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo $registro->findParentRow("TbDocumentoTipo")->toString(); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo $registro->mostrarNumero(); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo $registro->resumo; ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                            <?php echo ($arquivo)?$arquivo->miniatura(array("width" => 40, "link" => true)):""; ?>
                        </a>
                    </td>
                    <td>
                        <div class="btn-group pull-right">
                            <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "funcionario",
                                "id" => $registro->getId())); ?>" class="btn btn-white" data-toggle="tooltip" data-container="body" title="Funcionários">
                                <i class="icon-group"></i>
                            </a>
                            <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "view",
                                "id" => $registro->getId())); ?>" class="btn btn-white" data-toggle="tooltip" data-container="body" title="Visualizar">
                                <i class="icon-search"></i>
                            </a>
                            <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "editar",
                                "id" => $registro->getId())); ?>" class="btn btn-white" data-toggle="tooltip" data-container="body" title="Editar">
                                <i class="icon-cog"></i>
                            </a>
                            <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "excluir",
                                "id" => $registro->getId())); ?>" class="btn btn-danger  link_excluir" data-toggle="tooltip" data-container="body" title="Excluir">
                                <i class="icon-trash"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        <?php } ?>
    </table>
    <?php if ($this->registros && count($this->registros)) { ?>
    <div class="panel-footer">
        <?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
    </div>
    <?php } ?>
</section>