<section class="panel">
    <header class="panel-heading">Visualizar Documento Administrativo</header>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>Código:</dt>
            <dd><?php echo $this->registro->getId(); ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Tipo:</dt>
            <dd><?php echo $this->registro->findParentRow("TbDocumentoTipo")->toString(); ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Número:</dt>
            <dd><?php echo $this->registro->mostrarNumero(); ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Resumo:</dt>
            <dd><?php echo $this->registro->resumo; ?></dd>
        </dl>
    </div>
</section>