<?php
$tb_sistema = new TbSistema();
$sistema = $tb_sistema->pegaSistema();
if ($sistema) {
    $pf = $sistema->findParentRow("TbPessoaJuridica");
}
?>
<header class="header bg-black navbar navbar-inverse">
    <p><?php echo $pf['razao_social']; ?></p>
    <div class="collapse navbar-collapse pull-right">

        <!--
        <form class="navbar-form navbar-left m-t-sm" role="search">
            <div class="form-group">
                <div class="input-group input-s">
                    <input type="text" class="form-control input-sm no-border bg-dark" placeholder="Search">
                    <span class="input-group-btn">
          <button type="submit" class="btn btn-sm btn-success btn-icon"><i class="icon-search"></i></button>
        </span>
                </div>
            </div>
        </form>
        -->
        <ul class="nav navbar-nav navbar-right">
            <?php
            $usuario = TbUsuario::pegaLogado();
            $tb = new TbPacote();
            $pacotes = $tb->buscarPacotes($usuario);
            $atual = $tb->pegaAtual();


            if ($pacotes) {
                if($atual){
                    ?>

                    <li class="hidden-xs">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="icon-sitemap"></i> Pacote Atual: <?php echo $atual->descricao; ?>
                            <span class="badge up bg-info m-l-n-sm">2</span>
                        </a>
                        <section class="dropdown-menu animated fadeInUp input-s-lg">
                            <section class="panel bg-white">
                                <header class="panel-heading">
                                    <strong>Você possui <span class="count-n">2</span> pacotes disponíveis</strong>
                                </header>
                                <div class="list-group">
                                    <?php foreach ($pacotes as $pacote) { ?>
                                        <a href="<?php echo $this->url(array("controller" => "auth", "action" => "pacote", "id_pacote" => $pacote->getId())); ?>" class="media list-group-item">
                                            <span class="pull-left thumb-sm">
                                                <i class="<?php echo $pacote->icone; ?>"></i>
                                            </span>
                                            <?php echo $pacote->descricao; ?>
                                        </a>
                                    <?php } ?>
                                </div>
                                <footer class="panel-footer text-sm">
                                    <a href="<?php echo $this->url(array("controller" => "auth", "action" => "pacote")); ?>">Ver Todos</a>
                                </footer>
                            </section>
                        </section>
                    </li>
                <?php   }} ?>
            <?php
            /*
             * caixa do usuario
             *
             * nesta area as informações referente ao usuario logado são exibidas
             * nome de usuario, grupos do usuario e ultimo login
             */
            /* =============================================================================
               INFO USUARIO
               ========================================================================== */
            $acl = Escola_Acl::getInstance();
            $usuario = $acl->getUsuarioLogado();
            if ($usuario) {
                $txt_nome = $txt_cargo = $txt_setor = $txt_acesso = $txt_foto = $txt_foto_mini = "";

                $pf = $usuario->pega_pessoa_fisica();
                if ($pf) {
                    $txt_nome = $pf->nome;
                    $pessoa = $pf->pega_pessoa();
                    if ($pessoa) {
                        if ($pessoa->email) {
                            $email = $pessoa->email;
                        }
                        $foto = $pessoa->getFoto();
                        if ($foto) {
                            $txt_foto = $foto->miniatura(array("class" => "img-circle"));
                            $txt_foto_mini = Escola_Util::url(array("controller" => "arquivo", "action" => "view", "id" => $foto->getId()));
                        }
                    }
                    $tb = new TbFuncionario();
                    $funcionario = $tb->getPorPessoaFisica($pf);
                    if ($funcionario) {
                        $cargo = $funcionario->findParentRow("TbCargo");
                        if ($cargo) {
                            $txt_cargo = $cargo->toString();
                        }
                        $lotacao = $funcionario->pegaLotacaoAtual();
                        if ($lotacao) {
                            $setor = $lotacao->findParentRow("TbSetor");
                            if ($setor) {
                                $txt_setor = $setor->toString();
                            }
                        }
                    }
                }
                $login = $usuario->ultimoLogin();
                if ($login) {
                    $txt_acesso = new Zend_Date($login->data);
                }
                $grupos = $usuario->pegaTbGrupo();
                ?>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="thumb-sm avatar pull-left m-t-n-xs m-r-xs">
                        <?php if ($txt_foto_mini) { ?>
                            <img src="<?php echo $txt_foto_mini; ?>" class="user-image" alt="User Image">
                        <?php } ?>
                        </span>
                        <?php echo $txt_nome; ?> <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu animated fadeInLeft">
                        <li>
                            <?php if ($txt_cargo) { ?>
                                <?php echo $txt_cargo; ?> <br />
                            <?php } ?>
                            <?php if ($txt_setor) { ?>
                                <?php echo $txt_setor; ?> <br />
                            <?php } ?>

                        </li>
                        <li>
                            <div class="wrapper">
                                <div class="clearfix m-b">
                                    <a href="#" class="pull-left thumb m-r">
                                        <?php if ($txt_foto_mini) { ?>
                                            <img src="<?php echo $txt_foto_mini; ?>" class="img-circle" alt="User Image">
                                        <?php } ?>
                                    </a>
                                    <div class="clear">
                                        <div class="m-t-xs m-b-xs"><strong><?php echo $txt_nome; ?></strong></div>
                                        <?php if ($txt_acesso) { ?>
                                            <small class="text-uc text-xs text-muted">Ultimo Acesso:</small>
                                            <p> <?php echo $txt_acesso; ?></p>
                                        <?php } ?>

                                    </div>
                                </div>
                                <div class="btn-group btn-group-justified m-b">
                                    <a href="<?php echo $this->url(array("controller" => "pessoal", "action" => "index")); ?>" class="btn btn-success btn-rounded">
                                    <span class="text">
                                      <i class="icon-eye-open"></i> Perfil
                                    </span>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => "auth", "action" => "logout")); ?>" class="btn btn-danger btn-rounded">
                                        <i class="icon-power"></i> Sair
                                    </a>
                                </div>
                                <div>
                                    <small class="text-uc text-xs text-muted"><strong>Grupo(s):</strong></small>
                                    <small class="text-uc text-xs text-muted">
                                        <?php if(count($grupos) > 1){
                                            $ultimo = array_pop($grupos);
                                            echo implode( ', ', $grupos ) . ' e ' . $ultimo;
                                        } else {
                                            echo implode('', $grupos );
                                        } ?>
                                    </small>
                                </div>
                            </div>
                        </li>
                    </ul>
                </li>
            <?php } ?>
        </ul>
    </div>
</header>