<section class="panel">
    <header class="panel-heading">Cadastro de Usuários</header>
    <div class="panel-body">
        <form action="<?php echo $this->url(array("action" => "editar")); ?>" method="post" id="formulario" class="formulario">
            <input type="hidden" name="id" id="id" value="<?php echo $this->registro->getId(); ?>" />
            <?php if ($this->registro->getId()) { ?>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="cpf">Código:</label>
                        <input type="text" name="codigo" class="form-control" value="<?php echo $this->registro->getId(); ?>" disabled/>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="cpf">C.P.F.:</label>
                        <input type="text" name="cpf"class="cpf form-control" value="<?php echo $this->registro->getPessoaFisica()->cpf; ?>" disabled/>
                    </div>
                </div>
            <?php } else { ?>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="cpf">C.P.F.:</label>
                        <input type="text" name="cpf" id="cpf" class="cpf form-control" value="<?php echo $this->registro->getPessoaFisica()->cpf; ?>" />
                    </div>
                </div>
            <?php } ?>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="nome">Nome:</label>
                    <input type="text" name="nome" id="nome" maxlength="60" value="<?php echo $this->registro->getPessoaFisica()->nome; ?>" class="form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="email">E-Mail:</label>
                    <input type="text" name="email" id="email" size="60" maxlength="60" value="<?php echo $this->registro->getPessoaFisica()->getPessoa()->email; ?>" class="form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table("id_usuario_situacao");
                $ctrl->setPkName("id_usuario_situacao");
                $ctrl->setModel("TbUsuarioSituacao");
                $ctrl->setValue($this->registro->id_usuario_situacao);
                $ctrl->setLabel("Situação: ");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="data_nascimento">Data de Nascimento:</label>
                    <input type="text" name="data_nascimento" id="data_nascimento" size="10" maxlength="10" value="<?php echo $this->registro->getPessoaFisica()->mostrarDataNascimento(); ?>" class="data form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table("id_estado_civil");
                $ctrl->setPkName("id_estado_civil");
                $ctrl->setModel("TbEstadoCivil");
                $ctrl->setValue($this->registro->getPessoaFisica()->id_estado_civil);
                $ctrl->setLabel("Estado Civil: ");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table_Crud_Pais("id_pais");
                $ctrl->setPkName("id_pais");
                $ctrl->setModel("TbPais");
                $ctrl->setLabel("País: ");
                $ctrl->setValue($this->id_pais);
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table_Crud_Uf("id_uf");
                $ctrl->setPkName("id_uf");
                $ctrl->setModel("TbUf");
                $ctrl->setValue($this->id_uf);
                $ctrl->setLabel("Unidade Federativa: ");
                $ctrl->set_id_pais("id_pais");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table_Crud_Municipio("nascimento_id_municipio");
                $ctrl->setPkName("id_municipio");
                $ctrl->setModel("TbMunicipio");
                $ctrl->setValue($this->id_municipio);
                $ctrl->setLabel("Município: ");
                $ctrl->set_id_uf("id_uf");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <?php
                    $fixo = $this->getRequest()->getPost("telefone_fixo");
                    if (!$fixo) {
                        $fixos = $this->registro->getPessoaFisica()->getPessoa()->getTelefones("f");
                        if ($fixos) {
                            $fixo = $fixos[0]->toString();
                        }
                    }
                    ?>
                    <label for="telefone_fixo">Telefone Fixo: </label>
                    <input type="text" name="telefone_fixo" id="telefone_fixo" size="15" maxlength="15" value="<?php echo $fixo; ?>" class="telefone form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <?php
                $celular = $this->getRequest()->getPost("telefone_celular");
                if (!$celular) {
                    $celulares = $this->registro->getPessoaFisica()->getPessoa()->getTelefones("c");
                    if ($celulares) {
                        $celular = $celulares[0]->toString();
                    }
                }
                ?>
                <div class="form-group">
                    <label for="telefone_celular">Telefone Celular: </label>
                    <input type="text" name="telefone_celular" id="telefone_celular" size="15" maxlength="15" value="<?php echo $celular; ?>" class="telefone form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="identidade_numero">RG:</label>
                    <input type="text" name="identidade_numero" id="identidade_numero" size="30" maxlength="30" value="<?php echo $this->registro->getPessoaFisica()->identidade_numero; ?>"  class="form-control"/>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="identidade_orgao_expedidor">Órgão Expedidor:</label>
                    <input type="text" name="identidade_orgao_expedidor" id="identidade_orgao_expedidor" size="20" maxlength="20" value="<?php echo $this->registro->getPessoaFisica()->identidade_orgao_expedidor; ?>"  class="form-control" />
                </div>
            </div>
            <div class="col-md-4">
                <?php
                $ctrl = new Escola_Form_Element_Select_Table("identidade_id_uf");
                $ctrl->setPkName("id_uf");
                $ctrl->setModel("TbUf");
                $ctrl->setValue($this->registro->getPessoaFisica()->identidade_id_uf);
                $ctrl->setLabel("Unidade Federativa: ");
                $ctrl->setAttrib('class', 'form-control');
                echo $ctrl->render($this);
                ?>
            </div>
            <?php
            $end = $this->registro->getPessoaFisica()->getPessoa()->getEndereco();
            echo $end->render($this); ?>
        </form>
    </div>
</section>