<?php $tb = new TbUsuario(); ?>
<section class="panel" id="idPesquisa" style="display: none">
    <header class="panel-heading">Opções de Pesquisa</header>
    <div class="panel-body">
        <form action="<?php echo $this->url(array("action" => "index")); ?>" method="post" id="formulario" class="formulario">
            <div class="col-md-4">
                <div class="form-group">
                    <label for="filtro_cpf">C.P.F.:</label>
                    <input type="text" name="filtro_cpf" id="filtro_cpf" value="<?php echo $this->getRequest()->getPost("filtro_cpf"); ?>" class="filtro cpf form-control"  />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="filtro_nome">Nome:</label>
                    <input type="text" class="filtro form-control" name="filtro_nome" id="filtro_nome" value="<?php echo $this->getRequest()->getPost("filtro_nome"); ?>" />
                </div>
            </div>
        </form>
    </div>
    <div class="panel-footer">
        <input type="submit" value="Pesquisar" class="acao btn btn-primary" />
        <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn btn-white" />
    </div>
</section>

<section class="panel">
    <header class="panel-heading">Lista de Usuários</header>
    <table class="table table-striped table-hover table-vcenter">
        <thead>
        <tr>
            <th>ID</th>
            <th>C.P.F.</th>
            <th>Nome</th>
            <th>E-Mail</th>
            <th>Situação</th>
            <th class="text-right">Operações</th>
        </tr>
        </thead>
        <?php if ($this->registros) { ?>
            <tbody>
            <?php
            foreach ($this->registros as $registro) {
                $usuario = $tb->getPorId($registro["id_usuario"]);
                $pf = $usuario->getPessoaFisica();
                ?>
                <tr>
                    <td width="40px">
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $usuario->getId())); ?>">
                            <?php echo $usuario->getId(); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $usuario->getId())); ?>">
                            <?php echo $this->formatCpf($pf->cpf); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $usuario->getId())); ?>">
                            <?php echo $pf->nome; ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $usuario->getId())); ?>">
                            <?php echo $pf->getPessoa()->email; ?>
                        </a>
                    </td>
                    <td width="250px">
                        <a href="<?php echo $this->url(array("action" => "view", "id" => $usuario->getId())); ?>">
                            <?php echo $usuario->findParentRow("TbUsuarioSituacao")->descricao; ?>
                        </a>
                    </td>
                    <td>
                        <div class="btn-group pull-right">
                            <a class="btn btn-white" data-container="body" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "view",
                                "id" => $usuario->getId())); ?>" title="Visualizar" data-toggle="tooltip">
                                <i class="icon-search"></i>
                            </a>
                            <a class="btn btn-white" data-container="body" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "editar",
                                "id" => $usuario->getId())); ?>"title="Alterar" data-toggle="tooltip">
                                <i class="icon-cog"></i>
                            </a>
                            <a class="btn btn-white" data-container="body" href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                "action" => "grupos",
                                "id" => $usuario->getId())); ?>" title="Grupos" data-toggle="tooltip" >
                                <i class="icon-group"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        <?php } ?>
    </table>
    <div class="panel-footer">
        <?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
    </div>
</section>
