<section class="panel">
    <header class="panel-heading">Visualizar Usuário</header>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>Código:</dt>
            <dd><?php echo $this->registro->getId(); ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>C.P.F.:</dt>
            <dd><?php echo $this->formatCpf($this->registro->getPessoaFisica()->cpf); ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Nome:</dt>
            <dd><?php echo $this->registro->getPessoaFisica()->nome; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>E-Mail:</dt>
            <dd><?php echo $this->registro->getPessoaFisica()->getPessoa()->email; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Situação:</dt>
            <dd><?php echo $this->registro->findParentRow("TbUsuarioSituacao")->descricao; ?></dd>
        </dl>
    </div>
</section>
